feat(upgrade): add menu and tray icon migration guide
tauri-apps/tauri-docs pull request #1398
Opened 2023-08-15 12:01 UTC by lucasfernog

2023-08-15 12:11 UTC, lorenzolewis commented
Will get this one merged soon. Is this another package that we need to build guides and API references around (outside of the plugins repo)?

2023-08-15 12:18 UTC, FabianLars commented
I'd say yes, it's basically the same as v1's menu & tray features in this regard which also have (or should have) their own docs.

2023-08-15 12:28 UTC, lucasfernog commented
Yeah we have a dedicated menu and tray documentation. I was planning on leaving that for another PR. @amrbashir is going to double check this migration to see if I missed anything.

2023-08-15 12:44 UTC, lorenzolewis commented
Cool. Once we get https://github.com/tauri-apps/tauri-docs/pull/1379 through then that should be a really good template to follow for those guide(s).

2023-08-15 15:57 UTC, amrbashir requested changes
Just a couple suggestions

2023-08-15 15:57 UTC, amrbashir commented on src/content/docs/2/guide/upgrade-migrate/from-tauri-1.mdx
> +            .icon("Show App", app.default_window_icon().cloned().unwrap())
The next release will change these

```suggestion
            .text("open-url", "Open URL")
            .check("toggle", "Toggle")
            .icon("show-app", "Show App", app.default_window_icon().cloned().unwrap())
```

2023-08-15 15:57 UTC, amrbashir commented on src/content/docs/2/guide/upgrade-migrate/from-tauri-1.mdx
> +- Use `tauri::menu::Submenu` instead of `tauri::Submenu`:
```suggestion
- Use `tauri::menu::Submenu` or `tauri::menu::SubmenuBuilder` instead of `tauri::Submenu`:
```

2023-08-15 15:57 UTC, amrbashir commented on src/content/docs/2/guide/upgrade-migrate/from-tauri-1.mdx
> +If you don't want all listeners to be triggered when a menu item is selected, do not share menu items and use dedicated instances instead.
```suggestion
If you don't want all listeners to be triggered when a menu item is selected, do not share menu items and use dedicated instances instead, that you could move into `tauri::Window/WindowBuilder::on_menu_event` closure.
```

2023-08-15 17:04 UTC, lucasfernog commented on src/content/docs/2/guide/upgrade-migrate/from-tauri-1.mdx
> +            } else if event.id().clone() == "toggle" {
```suggestion
            } else if event.id() == "toggle" {
```

2023-08-15 17:37 UTC, amrbashir approved these changes

2023-08-16 07:43 UTC, lorenzolewis commented
Just did a few ordering and structure changes to make it easier for support to link to the relevant places.

Right now these changes are coming from core directly, so there isn't anything on jumping over to plugin world. Would it be okay if we leave this one open for a little while until we reach a conclusion on that discussion? Discord thread: https://discord.com/channels/616186924390023171/1141270622656286731

I also don't see anything around JavaScript migration but I'm assuming that's because the previous APIs were only available on the Rust side? Perfectly fine if that's the case, just let me know and I can do a couple more tweaks to make it consistent with some of the other sections or to note that.

2023-08-16 12:43 UTC, amrbashir commented
The tray and menu didn't have JS APIs but the menu had an JS event which will need migration but I am still on Working on the menu JS APIs and haven't decided on how it will look like yet.

2023-08-17 09:22 UTC, lorenzolewis commented
> The tray and menu didn't have JS APIs but the menu had an JS event which will need migration but I am still on Working on the menu JS APIs and haven't decided on how it will look like yet.

Cool, let me just add a few notes to this PR to reflect that and then we'll get it merged in

2023-08-17 09:29 UTC, lorenzolewis commented
@amrbashir it's this JS API you're referring to that you're working on, correct? https://tauri.app/v1/api/js/window/#onmenuclicked

2023-08-17 09:41 UTC, lorenzolewis commented
If I can get a check on this commit for accuracy then this should be good to merge: https://github.com/tauri-apps/tauri-docs/pull/1398/commits/512a0815a33dee7df1b6fe17a40db73c916cc598

2023-08-17 11:31 UTC, amrbashir commented
> @amrbashir it's this JS API you're referring to that you're working on, correct? [tauri.app/v1/api/js/window/#onmenuclicked](https://tauri.app/v1/api/js/window/#onmenuclicked)

Yeah

2023-08-17 13:58 UTC, lucasfernog commented
> If I can get a check on this commit for accuracy then this should be good to merge: [512a081](https://github.com/tauri-apps/tauri-docs/commit/512a0815a33dee7df1b6fe17a40db73c916cc598)

Looks good @lorenzolewis

2023-08-17 16:37 UTC, merged