i18n(es): Translate frontend configurations index.mdx to Spanish
tauri-apps/tauri-docs pull request #1502
Opened 2023-09-03 10:38 UTC by OscarArranz

I've left a couple of works or expressions in English such as "checklist" and "static site generation" as I think developers are used to using these terms. If it's needed though I can come up with a translation for both.

2023-09-03 11:54 UTC, lorenzolewis requested changes
Amazing! Just a few tweaks on headings and the title as we prefer Title Case for those. At my Duolingo level of Spanish this looks good to me, but I'll wait to see if a native Spanish speaker has a review.

CC @dreyfus92 as I know you mentioned doing more Spanish translations, I wonder if you'd be able to help out with a review on this one as well?

2023-09-03 11:54 UTC, lorenzolewis commented on src/content/docs/es/2/guide/frontend/index.mdx
> +title: Configuración del frontend
```suggestion
title: Configuración del Frontend
```

2023-09-03 11:54 UTC, lorenzolewis commented on src/content/docs/es/2/guide/frontend/index.mdx
> +## Checklist de configuración
```suggestion
## Checklist de Configuración
```

2023-09-03 12:04 UTC, OscarArranz commented
> Amazing! Just a few tweaks on headings and the title as we prefer Title Case for those. At my Duolingo level of Spanish this looks good to me, but I'll wait to see if a native Spanish speaker has a review.
> 
> CC @dreyfus92 as I know you mentioned doing more Spanish translations, I wonder if you'd be able to help out with a review on this one as well?

Sure! I committed the change with the titles in Title Case 😉

2023-09-03 12:08 UTC, marc2332 requested changes
Just some small improvements

2023-09-03 12:08 UTC, marc2332 commented on src/content/docs/es/2/guide/frontend/index.mdx
> +:::tip[¿No ves un framework concreto?]
```suggestion
:::tip[¿No ves un framework en concreto?]
```

2023-09-03 12:08 UTC, marc2332 commented on src/content/docs/es/2/guide/frontend/index.mdx
> +Tauri es frontend agnóstico y soporta la mayoría de los frameworks de frontend sin necesidad de demasiada configuración. Sin embargo, en casos puntuales algún framework podría necesitar configuración
```suggestion
Tauri es agnóstico al frontend y soporta la mayoría de los frameworks de frontend sin necesidad de demasiada configuración. Sin embargo, en casos puntuales algún framework podría necesitar configuración extra para funcionar con Tauri. Debajo puedes consultar una lista de frameworks con sus configuraciones recomendadas.
```

2023-09-03 15:01 UTC, dreyfus92 requested changes
Awesome work @OscarArranz, I left you some minor suggestions 😁

2023-09-03 15:01 UTC, dreyfus92 commented on src/content/docs/es/2/guide/frontend/index.mdx
> +- Usa static site generation (SSG). Tauri no soporta alternativas basadas en servidores de manera oficial (como SSR).
```suggestion
- Usa la generación de sitios estáticos (SSG). Tauri no soporta alternativas basadas en servidores de manera oficial (como SSR).
```

2023-09-03 15:01 UTC, dreyfus92 commented on src/content/docs/es/2/guide/frontend/index.mdx
> +	<LinkCard title="Next.js" href="/2/guide/frontend/nextjs" />
```suggestion
	<LinkCard title="Next.js" href="/es/2/guide/frontend/nextjs" />
```

2023-09-03 15:01 UTC, dreyfus92 commented on src/content/docs/es/2/guide/frontend/index.mdx
> +	<LinkCard title="Nuxt" href="/2/guide/frontend/nuxt" />
```suggestion
	<LinkCard title="Nuxt" href="/es/2/guide/frontend/nuxt" />
```

2023-09-03 15:01 UTC, dreyfus92 commented on src/content/docs/es/2/guide/frontend/index.mdx
> +	<LinkCard title="Qwik" href="/2/guide/frontend/qwik" />
```suggestion
	<LinkCard title="Qwik" href="/es/2/guide/frontend/qwik" />
```

2023-09-03 15:01 UTC, dreyfus92 commented on src/content/docs/es/2/guide/frontend/index.mdx
> +	<LinkCard title="Svelte" href="/2/guide/frontend/svelte" />
```suggestion
	<LinkCard title="Svelte" href="/es/2/guide/frontend/svelte" />
```

2023-09-03 15:01 UTC, dreyfus92 commented on src/content/docs/es/2/guide/frontend/index.mdx
> +	<LinkCard title="Vite" href="/2/guide/frontend/vite" />
```suggestion
	<LinkCard title="Vite" href="/es/2/guide/frontend/vite" />
```

2023-09-03 15:01 UTC, dreyfus92 commented on src/content/docs/es/2/guide/frontend/index.mdx
> +	<LinkCard title="Webpack" href="/2/guide/frontend/webpack" />
```suggestion
	<LinkCard title="Webpack" href="/es/2/guide/frontend/webpack" />
```

2023-09-03 15:01 UTC, dreyfus92 commented on src/content/docs/es/2/guide/frontend/index.mdx
> +	<LinkCard title="Leptos" href="/2/guide/frontend/leptos" />
```suggestion
	<LinkCard title="Leptos" href="/es/2/guide/frontend/leptos" />
```

2023-09-03 15:01 UTC, dreyfus92 commented on src/content/docs/es/2/guide/frontend/index.mdx
> +	<LinkCard title="Sycamore" href="/2/guide/frontend/sycamore" />
```suggestion
	<LinkCard title="Sycamore" href="/es/2/guide/frontend/sycamore" />
```

2023-09-03 15:01 UTC, dreyfus92 commented on src/content/docs/es/2/guide/frontend/index.mdx
> +	<LinkCard title="Trunk" href="/2/guide/frontend/trunk" />
```suggestion
	<LinkCard title="Trunk" href="/es/2/guide/frontend/trunk" />
```

2023-09-03 15:01 UTC, dreyfus92 commented on src/content/docs/es/2/guide/frontend/index.mdx
> +	<LinkCard title="Yew" href="/2/guide/frontend/yew" />
```suggestion
	<LinkCard title="Yew" href="/es/2/guide/frontend/yew" />
```

2023-09-03 15:09 UTC, marc2332 commented on src/content/docs/es/2/guide/frontend/index.mdx
> +- Usa static site generation (SSG). Tauri no soporta alternativas basadas en servidores de manera oficial (como SSR).
I would keep `static site generation` tbh, it is more of a concept name rather than a literal meaning from how I read it it

2023-09-03 15:52 UTC, lorenzolewis commented
Unfortunately adding `/es/` for pages that rely on an English fallback will break the link-checker. I'm tracking this in https://github.com/HiDeoo/starlight-links-validator/issues/9. For the time being I'd recommend leaving any links to pages that ARE NOT translated pointing to their default (English) paths.

2023-09-03 15:53 UTC, lorenzolewis commented on src/content/docs/es/2/guide/frontend/index.mdx
> +	<LinkCard title="Yew" href="/2/guide/frontend/yew" />
https://github.com/tauri-apps/tauri-docs/pull/1502#issuecomment-1704340179

2023-09-03 15:53 UTC, lorenzolewis commented on src/content/docs/es/2/guide/frontend/index.mdx
> +	<LinkCard title="Trunk" href="/2/guide/frontend/trunk" />
https://github.com/tauri-apps/tauri-docs/pull/1502#issuecomment-1704340179

2023-09-03 15:54 UTC, lorenzolewis commented on src/content/docs/es/2/guide/frontend/index.mdx
> +- Usa static site generation (SSG). Tauri no soporta alternativas basadas en servidores de manera oficial (como SSR).
@OscarArranz I believe this is the last point and then this one is ready to be merged in! 🥳

2023-09-06 06:14 UTC, OscarArranz commented
I've resolved one thread with the /es/ links that was still open and updated the server side generation term, I think this should be ready to go!

2023-09-06 07:18 UTC, lorenzolewis approved these changes
Amazing 🤩 Thanks @OscarArranz and appreciate the awesome reviews @marc2332 and @dreyfus92

2023-09-06 07:18 UTC, merged