i18n(es): Translate `prerequisites/index.mdx`
tauri-apps/tauri-docs pull request #1506
Opened 2023-09-03 18:15 UTC by dreyfus92

Translated `prerequisites/index.mdx` to spanish 🇪🇸

2023-09-03 19:25 UTC, marc2332 requested changes
just some suggestions, nice work!! 💯

2023-09-03 19:25 UTC, marc2332 commented on src/content/docs/es/2/guide/prerequisites/index.mdx
> +3. [Configurar para Objetivos Móviles](#configurar-para-objetivos-móviles) (solo se requiere si se desarrolla para móviles)
`Objetivos` sounds incredible weird in this context, I would just say

```suggestion
3. [Configurar para Móvil](#configurar-para-móvil) (solo se requiere si se desarrolla para móviles)
```

2023-09-03 19:25 UTC, marc2332 commented on src/content/docs/es/2/guide/prerequisites/index.mdx
> +Sigue el enlace para comenzar para tu sistema operativo respectivo:
```suggestion
Sigue el enlace para comenzar según tu sistema operativo:
```

2023-09-03 19:25 UTC, marc2332 commented on src/content/docs/es/2/guide/prerequisites/index.mdx
> +Si tu distribución no está incluida arriba, es posible que desees consultar [Awesome Tauri en GitHub](https://github.com/tauri-apps/awesome-tauri#guides) para ver si se ha creado una guía.
```suggestion
Si tu distribución no está incluida arriba, puedes consultar [Awesome Tauri en GitHub](https://github.com/tauri-apps/awesome-tauri#guides) para ver si se ha creado una guía.
```

2023-09-03 19:25 UTC, marc2332 commented on src/content/docs/es/2/guide/prerequisites/index.mdx
> +Tauri usa [Xcode](https://developer.apple.com/xcode/resources/) varias dependencias de desarrollo de macOS e iOS.
```suggestion
Tauri usa [Xcode](https://developer.apple.com/xcode/resources/) y varias dependencias de desarrollo de macOS e iOS.
```

2023-09-03 19:25 UTC, marc2332 commented on src/content/docs/es/2/guide/prerequisites/index.mdx
> +<summary>¿Solo desarrollo para objetivos de escritorio?</summary>
```suggestion
<summary>¿Solo estás desarollando para escritorio?</summary>
```

2023-09-03 19:25 UTC, marc2332 commented on src/content/docs/es/2/guide/prerequisites/index.mdx
> +Siguiente: [Configurar para Objetivos Móviles](#configurar-para-objetivos-móviles) si deseas construir para Android e iOS. De lo contrario, [Crea un Proyecto](/2/guide/create/).
```suggestion
Siguiente: [Configurar para Móvil](#configurar-para-móvil) si deseas construir para Android e iOS. De lo contrario, [Crea un Proyecto](/2/guide/create/).
```

2023-09-03 19:25 UTC, marc2332 commented on src/content/docs/es/2/guide/prerequisites/index.mdx
> +## Configurar para Objetivos Móviles
```suggestion
## Configurar para Móvil
```

2023-09-03 19:25 UTC, marc2332 commented on src/content/docs/es/2/guide/prerequisites/index.mdx
> +Si deseas apuntar tu aplicación para Android o iOS, entonces hay algunas dependencias adicionales que necesitas instalar:
```suggestion
Si deseas compilar tu aplicación para Android o iOS, entonces hay algunas dependencias adicionales que necesitas instalar:
```

2023-09-03 19:25 UTC, marc2332 commented on src/content/docs/es/2/guide/prerequisites/index.mdx
> +5. Agrega los objetivos de Android con `rustup`:
```suggestion
5. Agrega los destinos de compilación de Android con `rustup`:
```

2023-09-03 19:25 UTC, marc2332 commented on src/content/docs/es/2/guide/prerequisites/index.mdx
> +Agrega los objetivos de iOS con `rustup` en Terminal:
```suggestion
Agrega los destinos de compilación de iOS con `rustup` en Terminal:
```

2023-09-03 20:35 UTC, dreyfus92 commented
Thank you so much for the review @marc2332 😄

2023-09-04 06:42 UTC, marc2332 approved these changes

2023-09-04 07:03 UTC, lorenzolewis approved these changes
Absolutely amazing, thank you @dreyfus92 and thanks @marc2332 for the thorough review 💪

2023-09-04 07:03 UTC, merged