feat: added text about writing code blocks
tauri-apps/tauri-docs pull request #1544
Opened 2023-09-13 12:30 UTC by simonhyll

#### What kind of changes does this PR include?

- New or updated content

#### Description

Added a section about writing code blocks as per discussions on Discord.

2023-09-13 13:56 UTC, lorenzolewis requested changes
Thanks for this! Although it has a lot of useful information on why we got to this, I think this should really be very prescriptive in "here's how we write code blocks". 

Take a look at the [translating guide](https://github.com/tauri-apps/tauri-docs/blob/next/.github/TRANSLATING.md) and see how it's very to-the-point for someone to be able to dive in and contribute without needing to read through all the context of _how_ you we got to a decision.

Hopefully that makes sense. The goal is to make it as straight to the point as possible so that writers can know the expectation and run with it.

2023-09-13 18:37 UTC, simonhyll commented
Yea I agree it's too long, just couldn't think of a more concise way of getting the point across than with examples >.< I can take a look at it again but no promises I'll get it done anytime soon, got a lot of my plate already. Might have to let my favourite employee ChatGPT take a look at it lol

2023-09-13 18:57 UTC, lorenzolewis commented
No prob. Just getting it all down is the hard bit, word smithing I can try to take a look at a bit later in my evening if I have time and make a few suggestions.

2023-09-14 02:31 UTC, dreyfus92 requested changes
Awesome job @simonhyll, I've left you a couple of suggestions, let me know what you think 😁

2023-09-14 02:31 UTC, dreyfus92 commented on .github/CONTRIBUTING.md
> +In general when you provide people with code samples you want to give them the highest code quality possible. However, this isn't always aligned with what's best for the user when it comes to showing
```suggestion
In general, when providing code samples, it's essential to offer users the highest possible code quality. However, this isn't always aligned with the best approach for showcasing a new API. For code blocks meant to convey simple, copy-paste-friendly code snippets demonstrating a particular API, we've found that it's better for the user experience to prioritize minimalism and clarity over high code quality, even if that means using helpful panic messages.
```

2023-09-14 02:31 UTC, dreyfus92 commented on .github/CONTRIBUTING.md
> +Take the following two code samples, the first one is code from a previous version of the Tauri documentation.
```suggestion
Consider the following two code samples, with the first one being from a previous version of the Tauri docs:
```

2023-09-14 02:31 UTC, dreyfus92 commented on .github/CONTRIBUTING.md
> +There clearly is an attempt made to provide the user with the start of some error handling, something closer towhat they might have in production. However, if a user doesn't have a window labeled `sp
```suggestion
In this code, there's an attempt to incorporate error handling, closer to what users might use in a production environment. However, if a user doesn't have a window labeled `splashscreen`, the code won't crash, and they'll have to figure out the issue themselves. To address this in a proper way, we could, for example, add an else statement and panic within it. But is that considered high-quality code? We could also switch to a `match` statement, add a custom error message, or use `?` to raise the error, and so on.
```

2023-09-14 02:31 UTC, dreyfus92 commented on .github/CONTRIBUTING.md
> +There's simply no end to how many improvements can be made to the code provided. By adopting our approach of making simpler more panic prone code we can get the best of both worlds, easy to follow co
```suggestion
The possibilities for code improvement are endless. By adopting our approach of simplifying the code and making it more prone to panics, we can achieve the best of both worlds—code that's easy to follow and provides users with straightforward error messages explaining what went wrong.
```

2023-09-14 02:31 UTC, dreyfus92 commented on .github/CONTRIBUTING.md
> +This simplified version is no beauty and we hope nobody actually uses it in their production environment, but it gets the point across and helps users debug issues by themselves. Error handling is so
```suggestion
This simplified version may not be the epitome of elegance, and we hope users won't actually implement it in their production environments. However, it effectively conveys the point and empowers users to diagnose and debug issues on their own. While error handling is a substantial topic that deserves more in-depth coverage, showcasing an API is best achieved with as few lines as possible, coupled with expressive panic messages.
```

2026-08-06 18:59 UTC, closed without merging