Create clipboard guide #1475
tauri-apps/tauri-docs pull request #1604
Opened 2023-10-09 22:08 UTC by vasfvitor

- New or updated content
#### Description
- Address #1475 but not fully 

The content is based on the [README.md](https://github.com/tauri-apps/plugins-workspace/tree/v2/plugins/clipboard-manager) from the plugin's repo but I'm not sure about the use of `assert`, shouldn't be `console.assert`?

Still have to write the Rust part.

I'm looking at writing the other plugins guides, is it enough to adapt the content from each plugin's README.md*? I could just copy over and adapt. But my intention is to first try to use locally when possible.

\* Most stubs give v2 plugin README as a reference to get started, and at least [windows customization](https://beta.tauri.app/features/window-customization/) points to [v1 docs](https://tauri.app/v1/guides/features/window-customization/).

Since I'm learning Tauri as I write these docs, I don't want to claim this current issue, for me there's no problem if someone else does.

2023-10-09 22:13 UTC, vasfvitor commented
The overall structure is based on the Notification plugin docs, and in there it has:

{/* TODO: Demo component */}

and 

{/* TODO: Link to which language to use, frontend vs. backend guide when it's made */}

That I copied over this current guide but I'm don't know what they refer to. Is the aim that each plugin have a guide and a demo component for every (not every) JS and Rust frameworks? Or just vanilla?

2023-10-10 08:16 UTC, lorenzolewis requested changes
Awesome contribution @vasfvitor, thanks for putting this in! Just a few pieces of feedback and I think this one looks good to get merged in 💪

2023-10-10 08:16 UTC, lorenzolewis commented on src/content/docs/features/clipboard.mdx
> +assert(await readText(), 'Tauri is awesome!');
```suggestion
const content = await readText()
console.log(content)
// Prints "Tauri is awesome!" to the console
```

I wonder if something like this could be more familiar to JS devs instead of assert?

2023-10-10 08:16 UTC, lorenzolewis commented on src/content/docs/features/clipboard.mdx
> +
Is the allowlist config that's covered in https://tauri.app/v1/api/js/clipboard/ still required? If not then we could also add that to our migration guide in https://beta.tauri.app/guides/upgrade-migrate/from-tauri-1/#tauri-configuration to say it's been removed as well.

2023-10-10 15:11 UTC, vasfvitor commented on src/content/docs/features/clipboard.mdx
> +
The allowlist isn't required anymore. It's already covered in the docs v2 you refered.
(image from the migration link)
![image](https://github.com/tauri-apps/tauri-docs/assets/61759797/90a6e6e9-4b9e-472c-b842-6118aa62d090)

2023-10-11 08:53 UTC, lorenzolewis commented on src/content/docs/features/clipboard.mdx
> +
Good catch, I hadn't used it yet so wasn't 100% sure, thank you!

2023-10-11 08:54 UTC, lorenzolewis approved these changes

2023-10-11 08:56 UTC, lorenzolewis commented
Thanks @vasfvitor ! To answer your original questions:

> I'm looking at writing the other plugins guides, is it enough to adapt the content from each plugin's README.md*? I could just copy over and adapt. But my intention is to first try to use locally when possible.

I think this is a really good start, and then note any gaps (like the Rust part you did here) so we can keep track of them. That does cause some duplication between the READMEs and what we have in the docs, but I don't think that's an issue as we start to treat the docs as the main source for references and documentation.

2023-10-11 08:56 UTC, merged