i18zh-cn: Guides and Features
tauri-apps/tauri-docs pull request #1617
Opened 2023-10-14 03:16 UTC by Embers-of-the-Fire

#### What kind of changes does this PR include?

- Translated content

#### Description

This PR offers translation for most i18n-able documentation over Tauri2.

All pages listed on the translation status(currently) are translated, except for migration guides from Tauri1.

File list:

- features/index.mdx
- features/notification.mdx
- guides/frontend/index.mdx
- guides/frontend/nextjs.mdx
- guides/frontend/nuxt.mdx
- guides/frontend/trunk.mdx
- guides/plugins/develop-mobile.mdx
- guides/plugins/index.mdx
- guides/prerequisites/index.mdx
- index.mdx
- i18n/zh-CN.json: ui text i18n

2023-10-14 12:28 UTC, lorenzolewis reviewed
I haven't had a chance to do a full review to check all of the links etc. but just put a question on `zh-CN.json` as I don't believe it's needed.

@dklassic is this something you'd be able to help out on with a review when you have a moment?

2023-10-14 12:28 UTC, lorenzolewis commented on src/content/i18n/zh-CN.json
I don't think this file is needed as all of these should already be populated from Starlight directly via https://github.com/withastro/starlight/blob/main/packages/starlight/translations/zh-CN.json

2023-10-14 13:28 UTC, dklassic commented on src/content/i18n/zh-CN.json
I took a quick look and indeed all those strings are already populated from Starlight. Though by doing so the strings can be overridden, so maybe the question to be asked is whether or not we allow the override if deemed necessary by contributor. 

Though in this case I don't think there's necessity for overriding, because this particular part provides no substantial improvement from the one provided by Starlight.

2023-10-14 13:31 UTC, dklassic commented on src/content/i18n/zh-CN.json
> +	"search.shortcutLabel": "（点击 / 以搜索）",
In this context, `press /` is a keyboard shortcut, so instead of `点击` (click), `按` is a much better fit.

2023-10-14 13:31 UTC, dklassic commented on src/content/i18n/zh-CN.json
> +	"page.previousLink": "下一页",
This should be `上一页`

2023-10-14 13:32 UTC, dklassic commented on src/content/i18n/zh-CN.json
> +	"page.nextLink": "上一页",
This should be `下一页`

2023-10-14 14:00 UTC, dklassic commented
Thanks for contributing!

I'll focus more on providing general direction for improvements and some formatting nitpicks here.

2023-10-14 15:09 UTC, dklassic requested changes

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/features/index.mdx
Might want to do another pass to ensure the consistency of terminologies. There are some inconsistency and overlap between `Feature`(功能, 特性), `Functionality`(特性), and `Recipe`(特性,秘诀).

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/features/notification.mdx
Though `native` is often translated as `本地` in zh-CN, it might be less confusing to translate it as `原生` to prevent confusion with `local`.

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/features/notification.mdx
> +    3. 如果您想要在 JavaScript 中使用通知提示，请安装相应的npm包：
```suggestion
    3. 如果您想要在 JavaScript 中使用通知提示，请安装相应的 npm 包：
```
Formatting nitpick.

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/frontend/nextjs.mdx
> +1. 下载 `internal-ip` 以用于移动端开发：
```suggestion
1. 安装 `internal-ip` 以用于移动端开发：
```

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/frontend/index.mdx
> +从概念上讲，Tauri 充当静态 Web 主机。你需要为 Tauri 提供一个文件夹，其中包含一些 HTML，CSS，Javascript 和可能的 WASM 组合，用于提供给 Tauri 支持的 webview 渲染器。
```suggestion
概念上 Tauri 如同静态 Web 主机。你需要为 Tauri 提供一个文件夹，其中包含一些 HTML、CSS、Javascript 甚至可能是 WASM，供给 Tauri 的 webview 渲染器显示。
```

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/frontend/nextjs.mdx
> +    // 在开发模式下，我们使用 internal-ip 为资产提供服务
```suggestion
    // 在开发模式下，我们使用 internal-ip 提供资产
```

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/frontend/nuxt.mdx
> +## Example Configuration
```suggestion
## 示例配置
```

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/frontend/nuxt.mdx
> +1. Update Tauri configuration:
```suggestion
1. 更新 Tauri 配置：
```

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/frontend/trunk.mdx
> +你需要使用 `cargo install --git https://github.com/amrbashir/trunk` 以下载 Truck 并在 `Trunk.toml` 中设置 `serve.ws_protocol = "ws"`
```suggestion
你需要在安装 Truck 时使用 `cargo install --git https://github.com/amrbashir/trunk` 并在 `Trunk.toml` 中设置 `serve.ws_protocol = "ws"`
```

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/plugins/develop-mobile.mdx
> +如果你有一个现有的插件，并且想添加安卓或 iOS 的功能，你可以使用 `plugin android add`和`plugin ios add`来添加构建移动端插件项目，并指导您完成所需的更改。
```suggestion
如果你有一个现有的插件，并且想添加安卓或 iOS 的功能，你可以使用 `plugin android add` 和 `plugin ios add` 来添加构建移动端插件项目，并指导您完成所需的更改。
```
Formatting nitpick.

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/plugins/develop-mobile.mdx
> +桌面实现使用 Rust 代码来实现功能，而移动端实现会向本地移动端代码库发送消息以执行功能并返回结果。如果两个实现存在共享逻辑，可以在`lib.rs`中定义：
```suggestion
桌面实现使用 Rust 代码来实现功能，而移动端实现会向本地移动端代码库发送消息以执行功能并返回结果。如果两个实现存在共享逻辑，可以在 `lib.rs` 中定义：
```
Formatting nitpick.

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/plugins/develop-mobile.mdx
> +一个安卓 Tauri 插件由一个扩展了 `app.tauri.plugin.Plugin` 的 Kotlin 类定义，并由 `app.tauri.annotation.TauriPlugin` 标注。 每个被标注为 `app.tauri.annotation.Command` 的方法都可以被 Rust 或 JavaScript 调用。
```suggestion
一个安卓 Tauri 插件的定义为一个扩展了 `app.tauri.plugin.Plugin` 并标注 `app.tauri.annotation.TauriPlugin` 的 Kotlin 类。每个被标注为 `app.tauri.annotation.Command` 的方法都可以被 Rust 或 JavaScript 调用。
```

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/plugins/index.mdx
> +这个指南是用于指导开发 Tauri 插件。如果您想要寻找关于当前可用的插件的列表及其使用说明，请前往[特征和菜谱列表](/zh-cn/features)。
The name of the page "List of Features & Recipes" here "特征和菜谱列表" is completely different from the translation you've provided "功能及特性列表".

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/plugins/index.mdx
> +插件可以挂载到 Tauri 的生命周期中：暴露需求 webview API 的 Rust 代码，使用 Rust、Kotlin 或 Swift 代码处理命令，以及更多……
```suggestion
插件可以挂载到 Tauri 的生命周期中，暴露需求 webview API 的 Rust 代码，使用 Rust、Kotlin 或 Swift 代码处理命令并能处理更多需求。
```

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/plugins/index.mdx
> +从设计上讲，Tauri Core 并不包含所有人都需要的功能。相反，它提供了一种将外部功能添加到名为插件的 Tauri 应用程序中的机制。
```suggestion
设计上 Tauri Core 只包含所有人都需要的功能。相对地，它提供了一种将外部功能添加到 Tauri 应用程序中的机制，名为插件。
```

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/plugins/index.mdx
> +## 命名转换
```suggestion
## 命名规范
```

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/plugins/index.mdx
> +默认情况下，Tauri 会在你的插件箱前面加上 `tauri-plugin-`。这有助于你的插件被 Tauri 社区发现，但不是必须的。初始化新插件项目时，必须提供其名称。生成包名称将为 `tauri-plugin-{plugin-name}`，JavaScript NPM包名称为 `tauri-plugin-{plugin-name}-api`（尽管我们建议使用[NPM范围](https://
```suggestion
默认情况下，Tauri 会在你的插件 crate 前面加上 `tauri-plugin-`。这有助于你的插件被 Tauri 社区发现，但不是必须的。初始化新插件项目时，必须提供其名称。生成包名称将为 `tauri-plugin-{plugin-name}`，JavaScript NPM 包名称为 `tauri-plugin-{plugin-name}-api`（尽管我们建议使用 [NPM 范围](https://docs.npmjs.com/about-scopes)如果可能的话）。NPM 包的 Tauri 命名约定是 `@scope-name/plugin-{plugin-name}`。
```

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/prerequisites/index.mdx
> +通过访问 [WebView2 Runtime 下载区](https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section) 安装 WebView2。 下载“常青版独立安装程序（Evergreen Boostrapper）”并安装它。
```suggestion
通过访问 [WebView2 Runtime 下载区](https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section) 安装 WebView2。下载“常青版独立安装程序（Evergreen Boostrapper）”并安装它。
```
Formatting nitpick.

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/prerequisites/index.mdx
> +下一步：[配置移动端](#移动端配置) 如果你想要在 Android 或 iOS 上开发应用。否则前往 [创建新项目](/guides/create/)。
```suggestion
下一步：如果你想要在 Android 或 iOS 上开发应用前往[配置移动端](#移动端配置)。否则前往[创建新项目](/guides/create/)。
```

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/prerequisites/index.mdx
> +下一步：[配置 iOS](#ios) 或 [创建新项目](/guides/create/).
```suggestion
下一步：[配置 iOS](#ios)或[创建新项目](/guides/create/)。
```
Formatting nitpick.

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/prerequisites/index.mdx
> +iOS 开发需要 Xcode，并且仅在 macOS 上可用。确保您在 [macOS 系统依赖项部分](#macos) 中安装了 Xcode 而不是 Xcode 命令行工具。
```suggestion
iOS 开发需要 Xcode，并且仅在 macOS 上可用。确保您在 [macOS 系统依赖项部分](#macos)中安装了 Xcode 而不是 Xcode 命令行工具。
```
Formatting nitpick.

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/prerequisites/index.mdx
> +下一步：[创建新项目](/guides/create/).
```suggestion
下一步：[创建新项目](/guides/create/)。
```

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/prerequisites/index.mdx
> +2. 安装 [Homebrew](https://brew.sh):
```suggestion
2. 安装 [Homebrew](https://brew.sh)：
```

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/prerequisites/index.mdx
> +1. 在终端中使用 `rustup` 将 iOS 添加为编译目标:
```suggestion
1. 在终端中使用 `rustup` 将 iOS 添加为编译目标：
```

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/prerequisites/index.mdx
> +3. 使用 Homebrew 安装 [Cocoapods](https://cocoapods.org):
```suggestion
3. 使用 Homebrew 安装 [Cocoapods](https://cocoapods.org)：
```

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/prerequisites/index.mdx
> +如果您在安装过程中遇到任何问题，请务必查看 [故障诊断指南](/guides/troubleshoot/) 或联系 [Tauri Discord](https://discord.com/invite/tauri) 以寻求帮助。
```suggestion
如果您在安装过程中遇到任何问题，请务必查看[故障诊断指南](/guides/troubleshoot/)或联系 [Tauri Discord](https://discord.com/invite/tauri) 以寻求帮助。
```
Formatting nitpick.

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/guides/prerequisites/index.mdx
> +现在，您已经安装了所有前置要求，您可以准备好 [创建您的第一个 Tauri 应用程序](/guides/create/)！
```suggestion
现在，您已经安装了所有前置要求，您可以准备好[创建您的第一个 Tauri 应用程序](/guides/create/)！
```
Formatting nitpick.

2023-10-14 15:09 UTC, dklassic commented on src/content/docs/zh-CN/index.mdx
> +        单个代码库。
```suggestion
        使用单个代码库为 Linux、macOS、Windows、Android 和 iOS 构建您的应用程序。
```

2023-10-15 03:54 UTC, dklassic requested changes
Additional note that it’s probably best to just use 你 instead of 您 as the document will just end up having a lot of inconsistent phrasing in the end.

2023-10-16 13:09 UTC, Embers-of-the-Fire commented on src/content/docs/zh-CN/features/index.mdx
Certainly, in my translation, I will use the terms 功能 for `Feature`, 特性 for `Functionality`, and 秘诀 for `Recipe`.

2023-10-16 15:06 UTC, dklassic approved these changes
LGTM, let's go!

2023-10-16 15:07 UTC, merged