feat: create OS Information guide #1484
tauri-apps/tauri-docs pull request #1642
Opened 2023-10-23 21:12 UTC by vasfvitor

#### What kind of changes does this PR include?
- New content

#### Description
I'm putting this out but I'm not sure what the Rust code, or even the JS should included, I mean, how much detail or step. Right now the Rust code is minimal, so is the JS, it's almost like the js-api reference. For comparison in the clipboard guide #1622, I've included three steps to use the Rust code, with the end goal of invoking in frontend.

2023-11-05 18:12 UTC, lorenzolewis commented
To your point on this being a JS/Rust API reference I agree. I think that instead of listing out each different function, we could instead just have on function (such as `platform`) and then add a sentence saying additional functions as available with links to the API docs for each one.

2023-11-06 01:53 UTC, vasfvitor commented
Is that how you imagined?

2023-11-06 12:17 UTC, lorenzolewis requested changes
Would just move this link to be further up at the top so the reader can more easily see it.

2023-11-06 12:17 UTC, lorenzolewis commented on src/content/docs/features/os-info.mdx
> +With this plugin you can query multiple information from current operational system, here is how you can utilize the OS Information plugin:
```suggestion
With this plugin you can query multiple information from current operational system. See all available functions in the [JavaScript API](/2/reference/js/os/) or [Rust API](https://docs.rs/tauri-plugin-os/2.0.0-alpha.4/tauri_plugin_os/) references.
```

2023-11-06 12:17 UTC, lorenzolewis commented on src/content/docs/features/os-info.mdx
> +See all available functions in the [JavaScript API](/2/reference/js/os/) or [Rust API](https://docs.rs/tauri-plugin-os/2.0.0-alpha.4/tauri_plugin_os/) references.
```suggestion
```

2023-11-06 19:37 UTC, lorenzolewis approved these changes
Awesome! And good catch with the docs.rs link

2023-11-06 19:38 UTC, merged