Draft: migrate `guides/development` to next
tauri-apps/tauri-docs pull request #1670
Opened 2023-11-08 06:47 UTC by vasfvitor

#### What kind of changes does this PR include?

- New or updated content
- Changes to the docs site code

#### Description

Pages: 
https://tauri.app/v1/guides/development/development-cycle
https://tauri.app/v1/guides/development/updating-dependencies

- Diff at https://github.com/tauri-apps/tauri-docs/commit/3b7adc3ba9da1fc80e6e3f98575bb2958692b9b0
- Sidebar updated according to https://starlight.astro.build/guides/sidebar/#autogenerated-groups
- Modified the card below from /development-cycle: bold text, caution box and code filenames/path:

v2 (next):
<img src='https://github.com/tauri-apps/tauri-docs/assets/61759797/e77ad1a5-75fa-459a-ad5d-b55c2b408660' width='480'>

Original from v1:
<img src='https://github.com/tauri-apps/tauri-docs/assets/61759797/1194f7d0-4827-4229-b798-0dba6e9123a2' width='480'>

sidebar preview:
<img src='https://github.com/tauri-apps/tauri-docs/assets/61759797/6dfdfb9b-6677-4756-b197-437b328a20f9' width='720'>

#### Personal Notes (can be ignored)

`import Tabs from '@theme/Tabs';`
`import TabItem from '@theme/TabItem';`

can be replaced by `import { Tabs, TabItem } from '@astrojs/starlight/components';` to place code, if needed
or  `import CommandTabs from '@components/CommandTabs.astro';` to place commands

This `import Command from '@theme/Command'`
to `import CommandTabs from '@components/CommandTabs.astro';`

The Command
`<Command name="dev" />
`
becomes
```
<CommandTabs
	npm="npm run tauri dev"
	yarn="yarn tauri dev"
	pnpm="pnpm tauri dev"
	cargo="cargo tauri dev"
/>
```

https://starlight.astro.build/guides/authoring-content/#note-aside
`
:::info About Cargo.toml and Source Control`
into 
`:::caution[About Cargo.toml and Source Control]`

`:::info` can be: `note`, `tip`, `caution` or `danger` depending on context.

2023-11-27 11:27 UTC, lorenzolewis requested changes
Thank you! @vasfvitor ! A few notes:

- KO and IT translations: I saw your message on Discord this morning (just getting back in). I think we should transfer those translations into this branch as well but keep them deactivated. I haven't looked into the best way to do this (whether via drafts, using an underscore prefix, etc.) but I saw you had a local draft with that so will take your guidance on that
- Instead of having all of the sub-pages in the sidebar I'd prefer to just keep the "parent" page, so in this case "Develop". Then on that landing page you could use the `LinkCard` component to jump out to those. One UX item I don't like with that is the parent's sidebar entry won't be highlighted when on a sub-page. I've put in a discussion for this in https://github.com/withastro/starlight/discussions/950 and I know that Astro's main docs are also wanting similar behaviour. We can always do a component override to get this functionality in the meantime.

2023-11-27 11:27 UTC, lorenzolewis commented on src/content/docs/fr/guides/develop/development-cycle.mdx
> +:::
```suggestion
:::note

Chaque framework possède ses propres outils de développement. Il n'entre pas dans le cadre de ce document de les couvrir tous ou de rester à jour.

:::
```

2023-11-27 11:27 UTC, lorenzolewis commented on src/content/docs/guides/develop.mdx
I'd like to keep this page as a sort of "jumping off" page for the respective sub-pages under the Develop section.

2023-11-27 11:27 UTC, lorenzolewis commented on src/content/docs/guides/develop/development-cycle.mdx
> +:::
```suggestion
:::note

Every framework has its own development tooling. It is outside of the scope of this document to cover them all or stay up to date.

:::
```

2023-11-27 11:27 UTC, lorenzolewis commented on src/content/docs/zh-CN/guides/develop/development-cycle.mdx
> +:::
```suggestion
:::note

每个框架都有自己的开发工具。 涵盖所有内容或保持最新状态超出了本文档的范围。

:::
```

2023-11-28 01:20 UTC, vasfvitor commented on src/content/docs/guides/develop.mdx
Ok, I'll undelete it. Also I'll keep an eye on those lines in mdx.

2023-11-28 01:30 UTC, vasfvitor commented
About the translations: Ok, I'll look what I've done here

About the highlight: I've been following the Astro Docs migration to Starlight and they at least solved this in their code as you can see here https://docs-git-fork-theotterlord-starlight-migration-astrodotbuild.vercel.app/en/tutorial/1-setup/
So I consider every parent page will have this `LinkCard` component.
I'll go through each PR this week

2023-11-28 02:12 UTC, vasfvitor commented
Don't know if this is trivial but I guess it's up to you. Consider that having descriptions we'd have to write each one, copy from pages contents (as we don't have yet unique descriptions for each page) . With this in mind the simplest way would be 3. List without description. It's already committed this way (3), but in case you want to change, please.

TODO: Highlight the sidebar. I guess a dedicated PR for this one is better.

Italian i18n have the /development pages but they are not translated

1. Grid with description:
<img width="60%" src="https://github.com/tauri-apps/tauri-docs/assets/61759797/3928eae3-490a-4cdf-af33-71adad04b70b"/>


<br/><br/>
2. Grid without description:
<img width="60%" src="https://github.com/tauri-apps/tauri-docs/assets/61759797/60fe008b-798c-4a6f-9d58-9c6d7db4b70a"/>


<br/><br/>
3. List without description
<img width="60%" src="https://github.com/tauri-apps/tauri-docs/assets/61759797/3bdd2276-fc96-4300-bd79-724cd43378c0"/>

<br/><br/>
4. List with description
<img width="60%" src="https://github.com/tauri-apps/tauri-docs/assets/61759797/c6855280-14ac-4dda-bd04-c43cc9d8a32f"/>

2023-11-29 12:17 UTC, lorenzolewis commented
Awesome! And yes, I heard Sarah say at one point that Astro docs wanted that sub-item highlighting, but didn't take the time to see if/how they'd implemented it. So awesome to see!

I prefer option 1 with the grid with descriptions. One approach you could use to reduce duplicating those descriptions would be to pull in the content collection entry and get the respective title and description (if available) from there. I've done a similar thing in this component: https://github.com/tauri-apps/tauri-docs/blob/next/src/components/list/Features.astro (note: I haven't tested if it works correctly for i18n'd pages, I'm 99% sure it does not).

I actually have been wanting to build on top of `LinkCard` to allow passing a slug to it and then have the component itself automatically pull in the respective i18n's title, description, and link and PR that upstream, but haven't had the chance. 

Would you be interested in wrapping `LinkCard` to give that functionality? Then that can be easily applied to the rest of the migrations as well.

2023-11-29 17:08 UTC, vasfvitor commented
As of now, all pages shares the same description from v1 docs. The ones in the image was copied from page contents as an example. And from what I've seen in v1 pages, it's the same deal: shared description from the `_category_.yml` file.

Just to be sure we'll settle with 1, then fallback to 2? Will we write copy for each page?

I'm not sure I follow you on the "PR that upstream" part. I understood: create a custom component and open a separated PR here for it to be available.

To update, I'm already playing with a new/replacement component (based on `Features.astro`) that works with i18n. 

Aiming to make available translated content and fallback in the list, and if I manage, add a "fallback" notice on the card.

So far it kinda works for both i18n translated and default pages, but not for fallback, yet. Almost there

2023-11-30 10:25 UTC, lorenzolewis commented
Sorry, I could have been a little more clear in my explanation, so my bad.

Let's go with how you currently have it setup for this PR (with just the title and link) and then we can work through #1717 in parallel then update once that's done (if needed). I'll put a few more comments on that PR directly for that.

Does that all sound alright? Ready to merge this in?

2023-11-30 15:38 UTC, vasfvitor commented
updated to be list, for now without description.
created index page for each i18n page
now it's ready

2023-11-30 17:16 UTC, lorenzolewis commented
Perfection! Thank you very much! Hopefully the other will be a bit easier now to push through.

2023-11-30 17:16 UTC, lorenzolewis approved these changes

2023-11-30 17:16 UTC, merged