i18n(zh-cn): Translation /features/clipboard.mdx
tauri-apps/tauri-docs pull request #1734
Opened 2023-12-06 05:17 UTC by Yaxnice301

i18(zh-CN): Translation /features/clipboard.mdx

2023-12-06 05:21 UTC, Yaxnice301 commented
Why did I add this page in the zh-cn directory, but it is not displayed in the menu bar? Did I forget to write some configuration?

2023-12-06 10:55 UTC, vasfvitor commented on src/content/docs/zh-CN/features/os-info.mdx
> +const platform = await platform();
could this wait until #1733 is in so lines 88, 90 are updated accordingly?

2023-12-06 14:12 UTC, vasfvitor commented on src/content/docs/zh-CN/features/os-info.mdx
> +const platform = await platform();
```suggestion
const currentPlatform = await platform();
```

2023-12-06 14:12 UTC, vasfvitor commented on src/content/docs/zh-CN/features/os-info.mdx
> +console.log(platform);
```suggestion
console.log(currentPlatform);
```

2023-12-06 14:31 UTC, Yaxnice301 commented
I don't understand, do you mean there will be an update to this document? If there is an update, just send me a message, and I will update the translation when I get the email.

2023-12-06 15:36 UTC, vasfvitor commented
>Why did I add this page in the zh-cn directory, but it is not displayed in the menu bar? Did I forget to write some configuration?

No no at all, I'm looking into it now and the issue is on the website. I'll open a pr to fix it soon.

> I don't understand, do you mean there will be an update to this document? If there is an update, just send me a message, and I will update the translation when I get the email.

exactly, I left a suggestion with the updated code, but you can look at the mentioned pr and make the changes yourself

thank you very much for this translations, I'm sorry for this trouble

2023-12-06 15:40 UTC, Yaxnice301 commented
#### I'm going to say something
- Thank you for your reply
- Nope

2023-12-11 18:35 UTC, lorenzolewis requested changes
Thank you very much for this @Yaxnice301 ! I merged in #1747 and #1735 for the issue you raised (thanks @vasfvitor !)

I put a comment on two of the pages as they are not ready to be translated right now (but I really appreciate the eagerness to contribute!) You can check https://beta.tauri.app/contribute/translate-status to see which pages are ready for translation in the future.

@dklassic would you be able to help with a review please?

2023-12-11 18:35 UTC, lorenzolewis commented on src/content/docs/zh-cn/features/file-system.mdx
This page is not ready to be translated because it is only a placeholder. Could you remove this file from the PR?

2023-12-11 18:35 UTC, lorenzolewis commented on src/content/docs/zh-cn/guides/create/index.mdx
This page is not ready to be translated because the content will be updated soon. Could you remove this file from the PR?

2023-12-13 12:20 UTC, dklassic requested changes
Thanks for contributing! The translation is generally in good shape but there are some formatting issues and missing translations from place to place. One thing in particular stand out is that both `clipboard` and `dialog` plugins have full translated names while `OS Information` is translated in the title but left untouched within the article, is there a reason behind this?

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/clipboard.mdx
> +    2. 修改 `lib.rs` 以初始化插件:
```suggestion
    2. 修改 `lib.rs` 以初始化插件：
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/clipboard.mdx
> +    1. 运行 `cargo add tauri-plugin-clipboard-manager` 将插件添加到项目依赖 `Cargo.toml` 中.
```suggestion
    1. 运行 `cargo add tauri-plugin-clipboard-manager` 将插件添加到项目依赖 `Cargo.toml` 中。
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/clipboard.mdx
> +    2. 修改 `lib.rs` 以初始化插件:
```suggestion
    2. 修改 `lib.rs` 以初始化插件：
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/clipboard.mdx
> +    3. If you'd like to manage the clipboard in JavaScript then install the npm package as well:
missing translation

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/clipboard.mdx
> +剪贴板插件在JavaScript和Rust中都可用。
```suggestion
剪贴板插件在 JavaScript 和 Rust 中都可用。
```
Formatting nitpick.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +    2. 修改 `lib.rs` 以初始化插件:
```suggestion
    2. 修改 `lib.rs` 以初始化插件：
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +    1. 运行 `cargo add tauri-plugin-dialog` 将插件添加到项目依赖 `Cargo.toml` 中.
```suggestion
    1. 运行 `cargo add tauri-plugin-dialog` 将插件添加到项目依赖 `Cargo.toml` 中。
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +    2. 修改 `lib.rs` 以初始化插件:
```suggestion
    2. 修改 `lib.rs` 以初始化插件：
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +    3. 如果您想在JavaScript中创建对话框，请同时安装npm包：
```suggestion
    3. 如果您想在 JavaScript 中创建对话框，请同时安装 npm 包：
```
Formatting nitpick.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +该对话框插件在JavaScript和Rust中都可用。以下是您可以使用它的方式：
```suggestion
该对话框插件在 JavaScript 和 Rust 中都可用。以下是您可以使用它的方式：
```
Formatting nitpick.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +使用 JavaScript:
```suggestion
使用 JavaScript：
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +使用 Rust:
```suggestion
使用 Rust：
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +查看所有 [对话框选项](/2/reference/js/dialog/) 在 JavaScript API 参考手册中。
```suggestion
查看所有[对话框选项](/2/reference/js/dialog/)在 JavaScript API 参考手册中。
```
Formatting nitpick.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +显示一个带有 `Ok` 按钮的对话框。 请注意：如何用户关闭对话框将返回 `false`.
```suggestion
显示一个带有 `Ok` 按钮的对话框。请注意：如何用户关闭对话框将返回 `false`。
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +`multiple` 选项控制对话框是否允许多选,当 `directory` 决定是否为文件夹选择。
```suggestion
`multiple` 选项控制对话框是否允许多选，当 `directory` 决定是否为文件夹选择。
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +打开一个文件/文件夹选择对话框
```suggestion
打开一个文件或文件夹选择对话框
```
Technically the same meaning but much better formatting simply using "或" here.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +打开一个 文件/文件夹 保存对话框.
```suggestion
打开一个文件或文件夹保存对话框.
```
Formatting correction and technically the same meaning but much better formatting simply using "或" here.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +如果您需要非阻塞操作，您可以改用 `show()`:
```suggestion
如果您需要非阻塞操作，您可以改用 `show()`：
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +显示一个带有 `Ok` 按钮的对话框。 请注意：如何用户关闭对话框将返回 `false`.
```suggestion
显示一个带有 `Ok` 按钮的对话框。请注意：如何用户关闭对话框将返回 `false`。
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +如果您需要非阻塞操作，您可以改用 `show()`:
```suggestion
如果您需要非阻塞操作，您可以改用 `show()`：
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +// 返回一个 文件路径 `Option`, 如何用户关闭了对话框则返回 `None`。
```suggestion
// 返回一个文件路径 `Option`，如果用户关闭了对话框则返回 `None`。
```
Typo fix and formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +If you need a non blocking operation you can use `show()` instead:
Missing translation.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +    // 返回一个 文件路径 `Option`, 如何用户关闭了对话框则返回 `None`。
```suggestion
    // 返回一个文件路径 `Option`，如果用户关闭了对话框则返回 `None`。
```
Typo fix and formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +代替方案:
```suggestion
代替方案：
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/dialog.mdx
> +        // 返回一个 文件路径 `Option`, 如何用户关闭了对话框则返回 `None`。
```suggestion
        // 返回一个文件路径 `Option`，如果用户关闭了对话框则返回 `None`。
```
Typo fix and formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/os-info.mdx
Is there a particular reason why both `clipboard` and `dialog` plugins have full translated names but this one in particular only has a translated title but left untranslated in the article?

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/os-info.mdx
> +    2. 修改 `lib.rs` 以初始化插件:
```suggestion
    2. 修改 `lib.rs` 以初始化插件：
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/os-info.mdx
> +    1. 运行 `cargo add tauri-plugin-os` 请插件添加到项目依赖 `Cargo.toml` 中.
```suggestion
    1. 运行 `cargo add tauri-plugin-os` 请插件添加到项目依赖 `Cargo.toml` 中。
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/os-info.mdx
> +    2. 修改 `lib.rs` 以初始化插件:
```suggestion
    2. 修改 `lib.rs` 以初始化插件：
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/os-info.mdx
> +    3. 如果您想在JavaScript中使用，请同时安装npm包：
```suggestion
    3. 如果您想在 JavaScript 中使用，请同时安装 npm 包：
```
Formatting nitpick.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/os-info.mdx
> +使用此插件，您可以从当前操作系统查询多个信息。在 [JavaScript API](/2/reference/js/os/) 或 [Rust API](https://docs.rs/tauri-plugin-os/) 中查看所有可用函数.
```suggestion
使用此插件，您可以从当前操作系统查询多个信息。在 [JavaScript API](/2/reference/js/os/) 或 [Rust API](https://docs.rs/tauri-plugin-os/) 中查看所有可用函数。
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/os-info.mdx
> +`platform` 返回一个描述所使用操作系统的字符串。该值在编译时设置。可能的值是 `linux`, `macos`, `ios`, `freebsd`, `dragonfly`, `netbsd`, `openbsd`, `solaris`, `android`, `windows`.
```suggestion
`platform` 返回一个描述所使用操作系统的字符串。该值在编译时设置。可能的值是 `linux`、`macos`、`ios`、`freebsd`、`dragonfly`、`netbsd`、`openbsd`、`solaris`、`android`、`windows`。
```
Formatting correction.

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/os-info.mdx
> +// Prints "windows" to the terminal
untranslated comment?

2023-12-13 12:20 UTC, dklassic commented on src/content/docs/zh-cn/features/clipboard.mdx
> +            // Initialize the plugin
untranslated comment?

2024-06-05 10:15 UTC, Embers-of-the-Fire commented on src/content/docs/zh-cn/features/dialog.mdx
> +    <TabItem label="Automatic">
Missing translation.

2024-06-05 10:16 UTC, Embers-of-the-Fire commented on src/content/docs/zh-cn/features/dialog.mdx
> +    <TabItem label="Manual">
Missing translation.

2024-06-05 10:17 UTC, Embers-of-the-Fire commented on src/content/docs/zh-cn/guides/create/index.mdx
> +我们建议从基础的模版开始 (无框架的的HTML、CSS 和 JavaScript)。你随时可以 [集成一个前端框架](/guides/create/existing-project)。
Missing whitespace.

2024-06-05 10:17 UTC, Embers-of-the-Fire commented on src/content/docs/zh-cn/guides/create/index.mdx
> +要开始使用 `create-tauri-app`的话，请在要设置项目的文件夹中运行以下命令之一。 如果您不确定使用哪个命令，我们建议在Linux和macOS上使用Bash命令，在Windows上使用PowerShell命令。
Missing whitespace.

2024-06-05 10:17 UTC, Embers-of-the-Fire commented on src/content/docs/zh-cn/guides/create/index.mdx
> +- 特定于前端框架的指南（现在仅限于React、Angular、Vue、Svelte和Solid）
Missing whitespace.

2026-08-06 18:59 UTC, closed without merging