i18(zh-cn): splashscreen
tauri-apps/tauri-docs pull request #1891
Opened 2024-02-28 13:59 UTC by MojaveHao

#### What kind of changes does this PR include?

- Translated content

2024-03-02 07:35 UTC, dklassic requested changes
Hi there, thanks for contributing! I think the translation is general nice so just some formatting nitpicks here and there and some consistency update on terminology and I think we're good to go.

2024-03-02 07:35 UTC, dklassic commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/guides/features/splashscreen.md
> +如果你的网页可能需要一些时间来加载，或者你需要在显示主窗口之前在Rust中运行初始化过程，那么启动画面可以改善用户的加载体验。
```suggestion
如果你的网页可能需要一些时间来加载，或者你需要在显示主窗口之前在 Rust 中运行初始化过程，那么启动画面可以改善用户的加载体验。
```

2024-03-02 07:35 UTC, dklassic commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/guides/features/splashscreen.md
> +首先，在`distDir`中创建一个包含初始屏幕的HTML文件。然后，更新`tauri.conf.json`:
```suggestion
首先，在 `distDir` 中创建一个包含初始屏幕的 HTML 文件。然后，更新 `tauri.conf.json`：
```

2024-03-02 07:35 UTC, dklassic commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/guides/features/splashscreen.md
> +如果你正在等待你的 Web 代码，你需要创建一个`close_splashscreen`[命令](command).
```suggestion
如果你正在等待你的 Web 代码，你需要创建一个 `close_splashscreen` [命令](command)。
```

2024-03-02 07:35 UTC, dklassic commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/guides/features/splashscreen.md
> +// 注册命令:
```suggestion
// 注册命令：
```

2024-03-02 07:35 UTC, dklassic commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/guides/features/splashscreen.md
> +最后，添加一个`invoke()`事件侦听器（或者随时调用它）：
```suggestion
最后，添加一个 `invoke()` 事件侦听器（或者随时调用它）：
```

2024-03-02 07:35 UTC, dklassic commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/guides/features/splashscreen.md
> +如果你正在等待 Rust 代码运行，请将其放入`setup`函数处理程序中，以便您可以访问该`App`实例:
```suggestion
如果你正在等待 Rust 代码运行，请将其放入 `setup` 函数处理程序中，以便您可以访问该 `App` 实例：
```

2024-03-02 07:35 UTC, dklassic commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/guides/features/splashscreen.md
> +        // 显示主屏幕
```suggestion
        // 显示主窗口
```

2024-03-02 07:35 UTC, dklassic commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/guides/features/splashscreen.md
> +      // 我们在新任务上执行初始化代码，这样应用程序就不会冻结。
```suggestion
      // 我们在新任务上执行初始化代码，这样应用程序就不会冻结
```

2024-03-02 07:35 UTC, dklassic commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/guides/features/splashscreen.md
> +  // 显示主屏幕
```suggestion
  // 显示主窗口
```

2024-03-02 12:38 UTC, dklassic approved these changes

2024-03-04 19:37 UTC, dreyfus92 approved these changes
Thank you peeps! LGTM ✅

2024-03-11 19:59 UTC, merged