i18n(zh-cn): Translate existing content in the features directory
tauri-apps/tauri-docs pull request #1921
Opened 2024-03-05 03:43 UTC by GuoJikun

#### What kind of changes does this PR include?

- Translated content

#### Description

this is a checklist.

- [x] `features/logging.mdx`
- [ ] `features/barcode-scanner.mdx`
- [ ] `features/cli.mdx`
- [ ] `features/deep-linking.mdx`
- [ ] `features/window-state.mdx`

2024-03-08 08:09 UTC, GuoJikun commented
@dklassic need review

2024-03-08 18:54 UTC, dklassic commented
I'm a bit busy atm I'll try find time to review it tmr.

2024-03-11 10:34 UTC, dklassic requested changes

2024-03-11 10:34 UTC, dklassic commented on src/content/docs/zh-cn/features/barcode-scanner.mdx
> +title: Barcode Scanner
```suggestion
title: 条形码扫描器
```

2024-03-11 10:34 UTC, dklassic commented on src/content/docs/zh-cn/features/cli.mdx
> +1. 通过将以下内容添加到 `Cargo.toml` 的文件中来安装 Core 插件。
```suggestion
1. 通过将以下内容添加到 `Cargo.toml` 的文件中来安装插件。
```

2024-03-11 10:34 UTC, dklassic commented on src/content/docs/zh-cn/features/cli.mdx
> +# alternatively with Git:
```suggestion
# 或者使用 Git
```
Since you're translating previous comment, might as well translate this one.

2024-03-11 10:34 UTC, dklassic commented on src/content/docs/zh-cn/features/cli.mdx
> +用户可以以 `./app tauri.txt dest.txt` 的格式运行你的应用程序，参数匹配映射将把 `source` 定义为 `"tauri.txt"`，把 `destination` 定义为 `"dest.txt"`.
```suggestion
用户可以以 `./app tauri.txt dest.txt` 的格式运行你的应用程序，参数匹配映射将把 `source` 定义为 `"tauri.txt"`，把 `destination` 定义为 `"dest.txt"`。
```

2024-03-11 10:34 UTC, dklassic commented on src/content/docs/zh-cn/features/deep-linking.mdx
> +title: Deep Linking
```suggestion
title: 深度链接
```

2024-03-11 10:34 UTC, dklassic commented on src/content/docs/zh-cn/features/deep-linking.mdx
> +请安装 deep-link 插件。
```suggestion
请安装深度链接插件。
```

2024-03-11 10:34 UTC, dklassic commented on src/content/docs/zh-cn/features/deep-linking.mdx
> +deep-link 有 JavaScript 和 Rust 两种版本。
```suggestion
深度链接有 JavaScript 和 Rust 两种版本。
```

2024-03-11 10:34 UTC, dklassic commented on src/content/docs/zh-cn/features/deep-linking.mdx
> +		// 通常需要event:default来监听 deep-link 事件
```suggestion
		// 通常需要 event:default 来监听深度链接事件
```

2024-03-11 10:34 UTC, dklassic commented on src/content/docs/zh-cn/features/deep-linking.mdx
I think we can just translate the plugin's name. Since you've already have it translated in the permission, let's use that.

2024-03-11 10:34 UTC, dklassic commented on src/content/docs/zh-cn/features/global-shortcut.mdx
> +# alternatively with Git:
```suggestion
# 或者使用 Git
```
Since you're translating previous comment, might as well translate this one.

2024-03-11 10:34 UTC, dklassic commented on src/content/docs/zh-cn/features/global-shortcut.mdx
> +2. M修改 `lib.rs` 来初始化插件。
```suggestion
2. 修改 `lib.rs` 来初始化插件。
```

2024-03-11 10:34 UTC, dklassic commented on src/content/docs/zh-cn/features/logging.mdx
> +2. 然后，插件的所有 api 都可以通过 JavaScript 的 guest 绑定使用:
```suggestion
2. 然后，插件的所有 api 都可以通过 JavaScript 的 guest 绑定使用：
```

2024-03-11 10:34 UTC, dklassic commented on src/content/docs/zh-cn/features/window-state.mdx
> +请安装 window-state 插件。
```suggestion
请安装窗口状态插件。
```

2024-03-11 10:34 UTC, dklassic commented on src/content/docs/zh-cn/features/window-state.mdx
> +1. 通过将以下内容添加到 `Cargo.toml` 的文件中来安装 Core 插件。
```suggestion
1. 通过将以下内容添加到 `Cargo.toml` 的文件中来安装插件。
```

2024-03-11 10:34 UTC, dklassic commented on src/content/docs/zh-cn/features/window-state.mdx
> +你也可以在 JavaScript 和 Rust 中访问 window-state 插件。
```suggestion
你也可以在 JavaScript 和 Rust 中访问窗口状态插件。
```

2024-03-12 01:28 UTC, GuoJikun commented on src/content/docs/zh-cn/features/deep-linking.mdx
> +		// 通常需要event:default来监听 deep-link 事件
Would it sometimes be better to keep the English text and add the translation in parentheses after it?
example:
deep-link（深度链接）
or
深度链接(deep-link)

2024-03-12 09:25 UTC, dklassic commented on src/content/docs/zh-cn/features/deep-linking.mdx
> +		// 通常需要event:default来监听 deep-link 事件
I think it comes down to whether the community is more familiar with the translation or the English terminology:
- if the community is more familiar with the translation, let's leave it translated and maybe use "深度链接（deep-link）" as the title if the familiarity is more iffy.
- if the community is more familiar with the English terminology, let's use "深度链接（deep-link）" as the title but keep all mentioning of the plugin in page to be plain "deep-link", similar to what you did for the CLI page.

I'm not particularly familiar with the Chinese community so I'll trust your judgement on this one.

2024-03-12 09:38 UTC, GuoJikun commented on src/content/docs/zh-cn/features/deep-linking.mdx
> +		// 通常需要event:default来监听 deep-link 事件
In the absence of consensus or a glossary, I think the second is better.(如果你懂汉语：在没有达成共识或没有术语对照表的情况下，我认为第二条更好。)

![image](https://github.com/tauri-apps/tauri-docs/assets/21582741/d6717e62-5dca-4209-9981-2ae4392fa9a6)

2024-03-12 10:26 UTC, dklassic commented on src/content/docs/zh-cn/features/deep-linking.mdx
> +		// 通常需要event:default来监听 deep-link 事件
Okay let's do just that!

Also yeah I can read Chinese which is why I'm responsible for reviewing Chinese translation haha. I'm sticking to English bc it's much easier to loop in other opinions when needed.

2024-03-13 01:33 UTC, GuoJikun commented on src/content/docs/zh-cn/features/deep-linking.mdx
> +		// 通常需要event:default来监听 deep-link 事件
start with next PR or this?

2024-03-13 02:14 UTC, dklassic commented on src/content/docs/zh-cn/features/deep-linking.mdx
> +		// 通常需要event:default来监听 deep-link 事件
Let's have it done in this PR.

2024-03-14 08:00 UTC, dklassic approved these changes

2024-03-14 08:07 UTC, dklassic approved these changes

2024-03-14 08:07 UTC, merged