i18(zh-cn): translate `references/v2/acl.mdx` and `references/v2/js/index.mdx`
tauri-apps/tauri-docs pull request #1960
Opened 2024-03-14 09:08 UTC by GuoJikun

#### What kind of changes does this PR include?

- Translated content

#### Description

translate contents:

- `references/v2/acl.mdx`
- `references/v2/js/index.mdx`

Fix link jump errors:

- `features/autostart.mdx`
- `features/barcode-scanner.mdx`
- `features/cli.mdx`
- `features/deeping-linking.mdx`
- `features/global-shortcut.mdx`
- `features/logging.mdx`
- `features/window-state.mdx`

2024-03-17 05:24 UTC, Embers-of-the-Fire commented on src/content/docs/zh-cn/references/v2/acl.mdx
> +通常你会将其设置为 `../gen/schemas/desktop-schema.json`或 `../gen/schemas/mobile-schema.json`，不过你也可以为特定的目标平台定义功能。
```suggestion
通常你会将其设置为 `../gen/schemas/desktop-schema.json` 或 `../gen/schemas/mobile-schema.json`，不过你也可以为特定的目标平台定义功能。
```

typo: missing whitespace

2024-03-17 05:25 UTC, Embers-of-the-Fire commented on src/content/docs/zh-cn/references/v2/acl.mdx
> +如果你想允许远程 URL 访问 Tauri 命令(这很危险，需要仔细配置)，你可以使用`context`属性。
```suggestion
如果你想允许远程 URL 访问 Tauri 命令(这很危险，需要仔细配置)，你可以使用 `context` 属性。
```

typo: missing whitespace

2024-03-22 06:45 UTC, GuoJikun commented
@Embers-of-the-Fire All done.

2024-03-22 10:49 UTC, Embers-of-the-Fire commented
> @Embers-of-the-Fire All done.

I'm not the manager of this repo, just happened to see this PR. You'd better contact @dklassic

2024-03-23 15:29 UTC, dklassic requested changes
Thanks for contributing! Just some extra nitpicks and I think we're good to go.

Some extra weird thing I see is that the sidebar doesn't seem to read the localized name properly here, might need to investigate later once we merged.

<img width="664" alt="截圖 2024-03-24 凌晨12 27 48" src="https://github.com/tauri-apps/tauri-docs/assets/9499899/4688fec2-2fbe-4de3-95e8-9d7761f8f2c5">

2024-03-23 15:29 UTC, dklassic commented on src/content/docs/zh-cn/references/v2/acl.mdx
> +默认情况下，该功能适用于所有目标，但您可以选择 linux、macOS、windows、iOS 和 android 目标的一部分。
```suggestion
默认情况下，该功能适用于所有目标，但您可以选择 Linux、macOS、Windows、iOS 和 Android 目标的一部分。
```

2024-03-23 15:29 UTC, dklassic commented on src/content/docs/zh-cn/references/v2/acl.mdx
> +为了缓解这种情况，Tauri 使用访问控制列表（ACL）来限制插件命令的访问。默认情况下，所有插件命令都被阻止，无法访问。若要启用对应用程序所需命令的访问，必须定义需要访问的权限列表。
```suggestion
为了缓解这种情况，Tauri 使用访问控制列表（Access Control List；ACL）来限制插件命令的访问。默认情况下，所有插件命令都被阻止，无法访问。若要启用对应用程序所需命令的访问，必须定义需要访问的权限列表。
```

2024-03-23 15:29 UTC, dklassic commented on src/content/docs/zh-cn/references/v2/js/index.mdx
Not quite sure if we need to initialize a localized page for this hummmmm.

But well, I guess this way when it points to API references it'll be marked with untranslated.

2024-03-23 15:54 UTC, GuoJikun commented on src/content/docs/zh-cn/references/v2/js/index.mdx
Switching the language to Chinese and clicking on this page shows that there's no translation. So, I did localization.

2024-03-23 18:06 UTC, lorenzolewis commented
@dklassic to localise the sidebar you'll need to do it in the config. I believe someone had already done it for another language there. This is because Starlight doesn't allow us to control how deep an auto-generated sidebar is created and so we had to hand-configure some of it there.

2024-03-23 18:20 UTC, lorenzolewis commented on src/content/docs/zh-cn/references/v2/js/index.mdx
Up to @dklassic but in general we only accepted localised pages that were listed on the i18n dashboard. This is a generated page which means if it's localised you won't be able to tell if it's changed or not (since the English version isn't committed).

2024-03-24 00:25 UTC, dklassic commented on src/content/docs/zh-cn/references/v2/js/index.mdx
I guess it’s best to stick to the policy and leave it untranslated for now and best to generate it for all languages if we’re to go this route.

2024-03-24 00:46 UTC, Embers-of-the-Fire commented
@dklassic Sidebar settings need to be set in the astro config file. I've discussed this in discord before, and my suggestion at the time was to manually write a script to split the localisation to prevent polluting the config file. Other admins seem to prefer to wait for upstream updates, but I can't recall any changes to the current internationalisation of astro regarding this.

2024-03-24 01:49 UTC, GuoJikun commented
I didn't see the i18n configuration in the astro profile.

2024-03-24 11:22 UTC, Embers-of-the-Fire commented
@GuoJikun You can find it in the `astro.config.mjs` file. Starting at line 98 when the sidebar is configured, there are already one or two localisation settings in there, but it's basically in a completely untranslated state.

2024-03-24 11:29 UTC, GuoJikun commented
> @GuoJikun You can find it in the `astro.config.mjs` file. Starting at line 98 when the sidebar is configured, there are already one or two localisation settings in there, but it's basically in a completely untranslated state.

key translations?

2024-03-25 03:30 UTC, GuoJikun commented on src/content/docs/zh-cn/references/v2/js/index.mdx
I need to delete the ` references/v2 / js/index. The MDX `? @dklassic

2024-03-25 05:17 UTC, dklassic commented on src/content/docs/zh-cn/references/v2/js/index.mdx
Yes let's remove it for now.

2024-03-25 05:24 UTC, GuoJikun commented on src/content/docs/zh-cn/references/v2/js/index.mdx
> Yes let's remove it for now.

Ok, removed.

2024-03-27 07:20 UTC, GuoJikun commented
If there are no problems and you have time, can we merge? @dklassic

2024-03-27 10:38 UTC, merged