[build-docs]: How to build your Tauri app documentation
tauri-apps/tauri-docs pull request #2189
Opened 2024-05-23 14:36 UTC by gabenddos

#### What kind of changes does this PR include?

- New build (how to generate the **bundles** **not how to develop/build an app**) documentation

#### Description

- Closes #2184 

#### Check List
- [x] Added Build section to the develop docs
- [ ] Build Overview page
- [ ] Build Prerequisites page
- [ ] Bundle Window Installer page
- [ ] Bundle Linux Installer page
- [ ] Bundle Mac Installer page
- [ ] Bundle for Android page
- [ ] Bundle for iOS page
- [ ] A Next section at the end of each bundle platform page that links to the `Distribute Docs`

2024-05-23 15:04 UTC, vasfvitor commented
you can, (and should, IMO) check v1 docs build section https://tauri.app/v1/guides/building/ and match to the migration guide https://v2.tauri.app/start/migrate/from-tauri-1/ to check for stuff that changed, it will be mostly tauri.conf settings and the use of plugins

If you have trouble in any part of the process please ask

notice that "sidecar" and "resources" is now on develop section, at least [sidecar it is](https://beta.tauri.app/develop/sidecar/)

could you move those url fixes to the other PR? are they needed here?

2024-05-23 16:19 UTC, simonhyll commented
Imo we shouldn't have a "Build" section, all the docs in that section can be put in either "Distribute" or "Develop" instead. The information is relevant but the structure and format is old. Part of the reason I don't feel it makes sense is because you always either build in development or you build for distribution, there's not really a step in-between when you build. So we should have articles about building and debugging in Develop, and if you distribute binaries then that's what the Distribute section is all about.

Also, what is the prerequisites page for? That'd just be the general prerequisites we have in Quick Start?

We could have `Develop > Build` and `Distribute > Build` perhaps? I don't want the sidebar to get too bloated, it's already pretty huge

2024-05-23 16:19 UTC, simonhyll requested changes
Imo we shouldn't have a "Build" section, all the docs in that section can be put in either "Distribute" or "Develop" instead. The information is relevant but the structure and format is old. Part of the reason I don't feel it makes sense is because you always either build in development or you build for distribution, there's not really a step in-between when you build. So we should have articles about building and debugging in Develop, and if you distribute binaries then that's what the Distribute section is all about.

Also, what is the prerequisites page for? That'd just be the general prerequisites we have in Quick Start?

We could have Develop > Build and Distribute > Build perhaps? I don't want the sidebar to get too bloated, it's already pretty huge

2024-09-03 08:52 UTC, tweidinger commented
I think all of the mentioned guides are already live. Feel free to correct me on what is still missing.

2026-08-06 18:59 UTC, closed without merging