[Migration] [Translation i18(fr)] Migrate debian and adding the french version for v2
tauri-apps/tauri-docs pull request #2191
Opened 2024-05-23 14:56 UTC by Sir-Thom

#### What kind of changes does this PR include?
- Migrate the doc for the configuration of the .deb package 
- Added the french version of the doc for the configuration of the .deb package 
- 
#### Description
This PR migrate the the configuration of the .deb package  and Add french translation for it 
- Closes #2190

2024-05-23 15:13 UTC, vasfvitor commented
hey, thanks for this and welcome :). Somebody (or me) will review this later, now I'm just wondering why was tauri submodule deleted?

2024-05-23 15:17 UTC, Sir-Thom commented
> hey, thanks for this and welcome :). Somebody (or me) will review this later, now I'm just wondering why was tauri submodule deleted?

Oops that  a  dumb mistake on my part it should be readded now

2024-05-23 15:18 UTC, vasfvitor commented
ok, no problem

2024-05-23 16:28 UTC, dreyfus92 reviewed
Salut @Sir-Thom, voici quelques suggestions 😁

2024-05-23 16:28 UTC, dreyfus92 commented on src/content/docs/_fr/distribute/debian.mdx
> +La version de base du paquet Debian généré par le bundler de Tauri, contient tout ce dont vous avez besoin pour distribuer votre application sur les distributions Linux basées sur Debian. Il définit
```suggestion
La version de base du paquet Debian généré par le bundler de Tauri, contient tout ce dont vous avez besoin pour distribuer votre application sur les distributions Linux basées sur Debian. Il définit les icônes de votre application, génère un fichier Desktop et spécifie les dépendances `libwebkit2gtk-4.0-37` et `libgtk-3-0`, avec `libappindicator3-1` si votre application utilise la zone de notification du système.
```

2024-05-23 16:28 UTC, dreyfus92 commented on src/content/docs/distribute/debian.mdx
> +If your app depends on additional system dependencies you can specify them in `tauri.conf.json > bundle > linux > deb `.
```suggestion
If your app depends on additional system dependencies you can specify them in `tauri.conf.json > bundle > linux > deb`.
```

2024-05-23 16:28 UTC, dreyfus92 commented on src/content/docs/_fr/distribute/debian.mdx
> +Si votre application dépend de dépendances système supplémentaires, vous pouvez les spécifier dans `tauri.conf.json > bundle > linux > deb `.
```suggestion
Si votre application dépend de dépendances système supplémentaires, vous pouvez les spécifier dans `tauri.conf.json > bundle > linux > deb`.
```

2024-05-24 01:45 UTC, dreyfus92 approved these changes
Merci @Sir-Thom, LGTM ✅

2024-06-28 10:56 UTC, simonhyll requested changes
Nice work, just needs a bit of fixing :)

2024-06-28 10:56 UTC, simonhyll commented on pnpm-lock.yaml
There's no need to commit an updated lockfile for translations

2024-06-28 10:56 UTC, simonhyll commented on src/content/docs/_fr/distribute/Pipelines/github.mdx
Stub files should not be committed to translations, it breaks the intended setup where you get shown the fallback english page

2024-06-28 10:56 UTC, simonhyll commented on src/content/docs/_fr/distribute/Pipelines/gitlab.mdx
No stub pages for translations

2024-06-28 10:56 UTC, simonhyll commented on src/content/docs/_fr/distribute/Pipelines/index.mdx
No stub pages for translations

2024-06-28 10:56 UTC, simonhyll commented on src/content/docs/_fr/distribute/app-store.mdx
No stub pages for translations

2024-06-28 10:56 UTC, simonhyll commented on src/content/docs/_fr/distribute/debian.mdx
> +import Stub from '@components/Stub.astro';
Unnecessary import

2024-06-28 10:56 UTC, simonhyll commented on src/content/docs/_fr/distribute/index.mdx
No stub pages for translations

2024-06-28 10:56 UTC, simonhyll commented on src/content/docs/_fr/distribute/play-store.mdx
No stub pages for translations

2024-06-28 10:56 UTC, simonhyll commented on src/content/docs/_fr/distribute/steam.mdx
No stub pages for translations

2024-06-28 10:56 UTC, simonhyll commented on src/content/docs/distribute/debian.mdx
>  import Stub from '@components/Stub.astro';
Unnecessary import now that it's been written

2024-09-02 03:24 UTC, tweidinger requested changes
Can you please double check the dependencies, as from my understanding it should be webkit2gtk `4.1` instead of `4.0` and not sure about the other libraries.

I would maybe remove the stub files in `_fr/distribute` as there is no content added and I think the file names already changed with recent PRs but this is not a blocker from my perspective.

2024-09-02 03:24 UTC, tweidinger commented on src/content/docs/distribute/debian.mdx
> +The stock Debian package generated by the Tauri bundler has everything you need to ship your application to Debian-based Linux distributions, defining your application's icons, generating a Desktop f
I think these are v1 dependencies and it won't work in v2

2024-09-02 03:24 UTC, tweidinger commented on src/content/docs/distribute/debian.mdx
> +      //... all linux related configurations go here
I think the v1 example was simpler to understand with example files (https://v1.tauri.app/v1/guides/building/linux#custom-files):
```
  "files": {
          "/usr/share/README.md": "../README.md", // copies the README.md file to /usr/share/README.md
          "usr/share/assets": "../assets/" // copies the entire assets directory to /usr/share/assets
        }
```

2024-09-03 08:02 UTC, tweidinger requested changes
I think this is good to go aside from the very small nitpick on the example file, which I will also port to v1 🙃 . Will approve once last suggestions are merged.

Thanks for the porting!

2024-09-03 08:02 UTC, tweidinger commented on src/content/docs/distribute/debian.mdx
> +          "usr/share/assets": "../assets/" // copies the entire assets directory to /usr/share/assets
```suggestion
          "/usr/share/assets": "../assets/" // copies the entire assets directory to /usr/share/assets
```
Very small nitpick that is also wrong in v1 docs.

2024-09-03 08:02 UTC, tweidinger commented on src/content/docs/fr/distribute/debian.mdx
> +          "usr/share/assets": "../assets/" // copies toutes le dossier assets dans /usr/share/assets
```suggestion
          "/usr/share/assets": "../assets/" // copies toutes le dossier assets dans /usr/share/assets
```
Very small nitpick that is also wrong in v1 docs.

2024-09-16 15:25 UTC, tweidinger approved these changes

2024-09-16 15:31 UTC, tweidinger commented
There is some prettyfier formatting check failing. Will fix once back at the laptop in some hours (otherwise feel free to fix yourself). Else good to go 👍

2024-09-17 04:40 UTC, merged