Add environment variables documentation
tauri-apps/tauri-docs pull request #2200
Opened 2024-05-24 17:30 UTC by stretch07

#### What kind of changes does this PR include?

- New or updated content

#### Description

- What does this PR change? Give us a brief description. 
Completes the Stub environment variables page located [here](https://v2.tauri.app/reference/environment-variables/)

2024-05-24 17:38 UTC, stretch07 commented
darn, I have no clue why the build is failing, it seems like something more should be escaped in the markdown but i cant figure out what it is

2024-05-24 17:42 UTC, vasfvitor commented
hey thanks very much for this, very much needed!

is it possible that you could provide the source for these env var? Or are they a compilation found in multiple places?

I'll take a quick look as why it's failing to build

2024-05-24 17:59 UTC, vasfvitor requested changes
Could you change the formatting to this pattern or something that is easier to navigate?

`ENV_VAR` : description
`ENV_VAR` : description
`ENV_VAR` : description

For instance, this page https://deploy-preview-2200--tauri-v2.netlify.app/start/migrate/from-tauri-1/#environment-variables-changes lists as this:

- `ENV_VAR` : description
- `ENV_VAR` : description
- `ENV_VAR` : description

I'm open to ideas, if you have anything in mind...

Some visual references: 
https://vitejs.dev/guide/env-and-mode#env-variables
https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime
https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

2024-05-26 04:20 UTC, stretch07 commented
> hey thanks very much for this, very much needed!
> 
> is it possible that you could provide the source for these env var? Or are they a compilation found in multiple places?
> 
> I'll take a quick look as why it's failing to build

they're practically directly copied from here:
https://github.com/tauri-apps/tauri/blob/dev/tooling/cli/ENVIRONMENT_VARIABLES.md

I'm not aware of v2 adding more environment variables but if so let me know

2024-05-26 04:25 UTC, vasfvitor commented
> they're practically directly copied from here

so for now I think this is good, but for the future a improvement could be made to import this file contents into the documentation as a component, so we get the benefit of having always up to date content. Eventually could add extra information, if needed.

If you're feeling you want to tackle this, let me know, if not, I'll just check the preview and merge this.

2024-05-26 04:27 UTC, vasfvitor commented
but now looking at it, the rendered content will be different. I'll merge this alright

2024-05-26 04:28 UTC, vasfvitor commented
thanks again

2024-05-26 04:28 UTC, merged

2024-05-26 04:29 UTC, vasfvitor commented on src/content/docs/reference/environment-variables.mdx
> -Integrate https://github.com/tauri-apps/tauri/blob/dev/tooling/cli/ENVIRONMENT_VARIABLES.md into this page.
-_-

just saw this lol

2024-05-26 05:59 UTC, stretch07 commented
> > they're practically directly copied from here
> 
> so for now I think this is good, but for the future a improvement could be made to import this file contents into the documentation as a component, so we get the benefit of having always up to date content. Eventually could add extra information, if needed.
> 
> If you're feeling you want to tackle this, let me know, if not, I'll just check the preview and merge this.

that's actually a great idea, I'll get familiar with astro and look into how to do this. thanks!

2024-05-26 17:15 UTC, vasfvitor commented
we have a few pages that does this, here you can see one that is in progress but mostly done, https://github.com/tauri-apps/tauri-docs/blob/137bb35ed873efb0536368ba751ae085a60ad12f/src/components/Permissions.astro, just need to fix something upstream.

other than that you can take a look at the dir /packages that has [config-generator](https://github.com/tauri-apps/tauri-docs/tree/v2/packages/config-generator), [js-api-generator](https://github.com/tauri-apps/tauri-docs/tree/v2/packages/js-api-generator), [releases-generator](https://github.com/tauri-apps/tauri-docs/tree/v2/packages/releases-generator) that mix data importing and handling

overall everything that can be done this way, should be.