added updater page
tauri-apps/tauri-docs pull request #2207
Opened 2024-05-25 19:27 UTC by 0PandaDEV

#### What kind of changes does this PR include?
- added updater page

#### Description
Most of the content is inspired by the old [v1 version](https://tauri.app/v1/guides/distribution/updater) but with updated methods and more clearer instructions.

- [ ] Checked Grammar spelling

2024-05-27 18:27 UTC, vasfvitor requested changes
hey, thank you for this, content will be reviewed soon, for now a few changes to the code

2024-05-27 18:27 UTC, vasfvitor commented on src/content/docs/plugin/updater.mdx
> +</Tabs>
could you replace these with command tabs, you can place bun too, right now the component doesn't have support but there's a PR to fix that.

2024-05-27 18:27 UTC, vasfvitor commented on src/content/docs/plugin/updater.mdx
> +</Tabs>
same

2024-05-27 18:27 UTC, vasfvitor commented on src/content/docs/plugin/updater.mdx
> +  ```zsh
```suggestion
  ```sh frame=none
```
we usually use ```sh

2024-05-27 18:27 UTC, vasfvitor commented on src/content/docs/plugin/updater.mdx
> +  ```cmd
```suggestion
  ```ps frame=none
```
and ps for windows commands

2024-05-27 18:27 UTC, vasfvitor commented on src/content/docs/plugin/updater.mdx
> +```json
```suggestion
```json title=tauri.conf.json
```

2024-05-28 19:41 UTC, vasfvitor submitted a review, later dismissed
Could you add 2 TODO comments on the top of the file, one for adding CrabNebula tip about updater and another to add a tip about GitHub action

Still missing the api usage, both Rust and Javascript, it can be as simples as this:

https://beta.tauri.app/start/migrate/from-tauri-1/#migrate-to-updater-plugin

https://github.com/tauri-apps/tauri-plugin-updater?tab=readme-ov-file#usage

And the permission list "updater:default", I'm not sure Tauri adds it by default, but it's important to list all the permissions from this table here:

https://github.com/tauri-apps/tauri-plugin-updater/blob/v2/permissions/autogenerated/reference.md

You can check other plugin guides to see how they done it so you can get an idea, for instance:

https://beta.tauri.app/plugin/barcode-scanner/#usage
https://beta.tauri.app/plugin/barcode-scanner/#permissions

Permission can go in the end of the guide. Usage I'm not so sure, it could go after Setup or before permissions, see what do you think it's best for someone trying it out.

And I think this does it, let me know if you have any ideas

2024-05-28 19:41 UTC, vasfvitor commented on src/content/docs/plugin/updater.mdx
> +  | `notes`        | Notes about the update. This will be displayed in the dialog Tauri generates.                                                               |
```suggestion
  | `notes`        | Notes about the update.                                                  |
```

2024-05-28 19:41 UTC, vasfvitor commented on src/content/docs/plugin/updater.mdx
> +  | `notes`        | Notes about the update. This will be displayed in the dialog Tauri generates.                                                               |
in v2 there's no default dialog anymore, one have to manually create if needed

2024-05-28 19:41 UTC, vasfvitor commented on src/content/docs/plugin/updater.mdx
> +  | `notes`        | Notes about the update. This will be displayed in the dialog Tauri generates.                                                               |
```suggestion
  | `notes`        | Notes about the update.                                                               |
```

2024-05-28 19:41 UTC, vasfvitor commented on src/content/docs/plugin/updater.mdx
> +- Linux: On Linux, Tauri will create a .tar.gz archive from the AppImage inside the target/release/bundle/appimage/ folder:
```suggestion
- Linux: On Linux, Tauri will create a .tar.gz archive from the AppImage inside the `target/release/bundle/appimage/` folder:  
```

same on others path on this page

2024-05-28 19:41 UTC, vasfvitor commented on src/content/docs/plugin/updater.mdx
> +  $env:TAURI_KEY_PASSWORD=""
```suggestion
  $env:TAURI_SIGNING_PRIVATE_KEY_PASSWORD=""
```

https://beta.tauri.app/start/migrate/from-tauri-1/#environment-variables-changes

2024-05-28 19:41 UTC, vasfvitor commented on src/content/docs/plugin/updater.mdx
> +  export TAURI_KEY_PASSWORD=""
```suggestion
  export TAURI_SIGNING_PRIVATE_KEY_PASSWORD=""
```

2024-06-11 19:36 UTC, FabianLars commented
Let's worry about js/rust/permissions later. Thanks for the contribution!

2024-06-11 19:38 UTC, FabianLars approved these changes

2024-06-11 19:55 UTC, merged