i18(zh-cn): Synchronizing content
tauri-apps/tauri-docs pull request #2231
Opened 2024-05-31 08:33 UTC by GuoJikun

#### What kind of changes does this PR include?

- Translated content

#### Description

2024-06-03 10:31 UTC, dklassic requested changes
Hi, thanks for contributing.

Your recent contributions seems to be derivative of machine assisted translation, and while I'm totally open to the idea of using MT in translating Tauri docs I'd like to ask you kindly to put more effort into validating the content less another obvious error such as `Tauri` being translated into `金牛座` made it through.

2024-06-03 10:31 UTC, dklassic commented on src/content/docs/zh-cn/start/frontend/nextjs.mdx
> +    版本 8.0.0 不起作用！
```suggestion
    版本 8.0.0 **无法**运作！
```
Maybe a better wording choice.

2024-06-03 10:31 UTC, dklassic commented on src/content/docs/zh-cn/start/frontend/nextjs.mdx
> +1.  ##### 更新金牛座配置
```suggestion
1.  ##### 更新 Tauri 配置
```

2024-06-03 10:31 UTC, dklassic commented on src/content/docs/zh-cn/start/frontend/nextjs.mdx
> +Next.js 是一个基于 React 的元框架。了解更多关于 Next.js 的信息，请访问 https://nextjs.org 。本指南适用于 Next.js 14.2.3 版本。
```suggestion
Next.js 是一个基于 React 的元框架。要了解更多关于 Next.js 的信息，请访问 https://nextjs.org 。本指南适用于 Next.js 14.2.3 版本。
```
wording adjustment.

2024-06-03 10:31 UTC, dklassic commented on src/content/docs/zh-cn/start/frontend/nuxt.mdx
> +Nuxt 是一个基于 Vue 的元框架。了解更多关于 Nuxt 的信息，请访问 https://nuxt.com 。本指南适用于 Nuxt 3.7版本。
```suggestion
Nuxt 是一个基于 Vue 的元框架。要了解更多关于 Nuxt 的信息，请访问 https://nuxt.com 。本指南适用于 Nuxt 3.7版本。
```
wording adjustment.

2024-06-03 10:31 UTC, dklassic commented on src/content/docs/zh-cn/start/frontend/nextjs.mdx
> +## 清单
```suggestion
## 检查清单
```
检查清单 should make more sense as a literal 清单 makes no sense.

2024-06-03 10:31 UTC, dklassic commented on src/content/docs/zh-cn/start/frontend/nuxt.mdx
> +## 清单
```suggestion
## 检查清单
```
检查清单 should make more sense as a literal 清单 makes no sense.

2024-06-03 10:31 UTC, dklassic commented on src/content/docs/zh-cn/start/frontend/trunk.mdx
> +Trunk 是一个用于 Rust 的 WASM 网络应用程序打包工具。了解更多关于 Trunk 的信息，请访问 https://trunkrs.dev 。本指南适用于 Trunk 0.17.5 版本。
```suggestion
Trunk 是一个用于 Rust 的 WASM 网络应用程序打包工具。要了解更多关于 Trunk 的信息，请访问 https://trunkrs.dev 。本指南适用于 Trunk 0.17.5 版本。
```
Wording adjustment.

2024-06-03 10:31 UTC, dklassic commented on src/content/docs/zh-cn/start/frontend/trunk.mdx
> +## 清单
```suggestion
## 检查清单
```
检查清单 should make more sense as a literal 清单 makes no sense.

2024-06-04 00:38 UTC, GuoJikun commented
> Hi, thanks for contributing.
> 
> Your recent contributions seems to be derivative of machine assisted translation, and while I'm totally open to the idea of using MT in translating Tauri docs I'd like to ask you kindly to put more effort into validating the content less another obvious error such as `Tauri` being translated into `金牛座` made it through.

Okay, I will pay attention.

2024-06-04 12:26 UTC, dklassic approved these changes

2024-06-04 12:26 UTC, merged