i18(zh-cn): translate `distribute/snapcraft.mdx`
tauri-apps/tauri-docs pull request #2398
Opened 2024-07-12 02:24 UTC by GuoJikun

#### Description

- What does this PR change? Give us a brief description. 
- Closes #

2024-07-16 02:12 UTC, GuoJikun commented
@vasfvitor Does this need to be changed?

![image](https://github.com/user-attachments/assets/0c95bcbc-9db5-438b-8492-64340f502dec)

2024-07-21 23:10 UTC, dklassic requested changes

2024-07-21 23:10 UTC, dklassic commented on src/content/docs/zh-cn/distribute/snapcraft.mdx
> +- `version` 变量`定义了版本，并且应该随着源代码库的每次更改而更新。
```suggestion
- `version` 变量定义了版本，并且应该随着源代码库的每次更改而更新。
```

2024-07-22 00:39 UTC, dklassic approved these changes

2024-07-22 03:21 UTC, GuoJikun commented
@dklassic 
![image](https://github.com/user-attachments/assets/7f43699f-e9eb-41aa-828e-b1b5aebaf829)

2024-07-22 03:33 UTC, dklassic commented
> @dklassic https://github.com/tauri-apps/tauri-docs/actions/runs/10032636847 ![image](https://private-user-images.githubusercontent.com/21582741/350827454-7f43699f-e9eb-41aa-828e-b1b5aebaf829.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MTk0NzUsIm5iZiI6MTcyMTYxOTE3NSwicGF0aCI6Ii8yMTU4Mjc0MS8zNTA4Mjc0NTQtN2Y0MzY5OWYtZTllYi00MWFhLTgyOGUtYjFiNWFlYmFmODI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDAzMzI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZGExMjFjM2Y5ZGFlMzVlNDFmNWIwYzhiZjZhNTAxOWM2M2JmOTYxYmI3ZDZhNDljZmYyN2NhYTE3NzBkMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SNppBGRK3a-x05dY9-XgHGf7SNR4W2TdBa2plRRQsWQ)

I think the workflow is just busted, we’re good.

2024-07-22 03:34 UTC, merged