i18n(zh-cn): Translate `start/migrate/from-tauri-2-beta.mdx`
tauri-apps/tauri-docs pull request #2505
Opened 2024-08-05 07:05 UTC by GuoJikun

#### Description

- What does this PR change? Give us a brief description. 
- Closes #

2024-08-07 12:00 UTC, dklassic requested changes
Some formatting nitpicks here and there and we should be good to go!

2024-08-07 12:00 UTC, dklassic commented on src/content/docs/zh-cn/start/migrate/from-tauri-2-beta.mdx
> +本指南将引导您将 Tauri2.0 beta 应用程序升级到 Tauri2.0 rc 版本。
```suggestion
本指南将引导您将 Tauri 2.0 Beta 应用程序升级到 Tauri 2.0 RC 版本。
```
Formatting nitpick.

2024-08-07 12:00 UTC, dklassic commented on src/content/docs/zh-cn/start/migrate/from-tauri-2-beta.mdx
> +从 beta 版到发布 rc 版，我们有几个重大变化。这些可以自动迁移(见上文)，也可以手动执行。
```suggestion
从 Beta 版到发布 RC 版，我们有几个重大变化。这些可以自动迁移（见上文），也可以手动执行。
```
Formatting nitpick.

2024-08-07 12:00 UTC, dklassic commented on src/content/docs/zh-cn/start/migrate/from-tauri-2-beta.mdx
> +我们在功能中改变了Tauri内置插件的处理方式 [PR #10390](https://github.com/tauri-apps/tauri/pull/10390).
```suggestion
我们在功能中改变了 Tauri 内置插件的处理方式 [PR #10390](https://github.com/tauri-apps/tauri/pull/10390)。
```
Formatting nitpick.

2024-08-07 12:00 UTC, dklassic commented on src/content/docs/zh-cn/start/migrate/from-tauri-2-beta.mdx
> +要从最新的 beta 版本迁移，您需要在您的能力中添加所有核心权限标识符 `core:`，或者切换到 `core:default` 权限并删除旧的核心插件标识符。
```suggestion
要从最新的 Bbeta 版本迁移，您需要在您的能力中添加所有核心权限标识符 `core:`，或者切换到 `core:default` 权限并删除旧的核心插件标识符。
```
Formatting nitpick.

2024-08-07 12:00 UTC, dklassic commented on src/content/docs/zh-cn/start/migrate/from-tauri-2-beta.mdx
> +我们对内置开发服务器的网络公开进行了更改 [PR #10437](https://github.com/tauri-apps/tauri/pull/10437) and [PR #10456](https://github.com/tauri-apps/tauri/pull/10456).
```suggestion
我们对内置开发服务器的网络公开在 [PR #10437](https://github.com/tauri-apps/tauri/pull/10437) 和 [PR #10456](https://github.com/tauri-apps/tauri/pull/10456) 进行了更改。
```
Wording fixes.

2024-08-07 12:00 UTC, dklassic commented on src/content/docs/zh-cn/start/migrate/from-tauri-2-beta.mdx
> +然后运行 `tauri ios dev --force-ip-prompt` 来选择iOS设备的TUN地址（以 **::2** 结尾）。
```suggestion
在这种情况下，我们默认使用开发服务器的公共网络地址，但有一种方法可以绕过这个问题，即打开 Xcode 以自动建立您的 macOS 机器与连接的 iOS 设备之间的连接，然后运行 `tauri ios dev --force-ip-prompt` 来选择 iOS 设备的 TUN 地址（以 **::2** 结尾）。
```
Formatting nitpick.

2024-08-07 12:00 UTC, dklassic commented on src/content/docs/zh-cn/start/migrate/from-tauri-2-beta.mdx
> +- 2.0.0-beta:
```suggestion
- 2.0.0-beta：
```
Formatting nitpick.

2024-08-07 12:00 UTC, dklassic commented on src/content/docs/zh-cn/start/migrate/from-tauri-2-beta.mdx
> +- 2.0.0-rc:
```suggestion
- 2.0.0-rc：
```
Formatting nitpick.

2024-08-08 00:33 UTC, GuoJikun commented on src/content/docs/zh-cn/start/migrate/from-tauri-2-beta.mdx
> +要从最新的 beta 版本迁移，您需要在您的能力中添加所有核心权限标识符 `core:`，或者切换到 `core:default` 权限并删除旧的核心插件标识符。
> Formatting nitpick.

Bbeta  ->  Beta

2024-08-08 01:31 UTC, GuoJikun commented on src/content/docs/zh-cn/start/migrate/from-tauri-2-beta.mdx
> +要从最新的 beta 版本迁移，您需要在您的能力中添加所有核心权限标识符 `core:`，或者切换到 `core:default` 权限并删除旧的核心插件标识符。
```suggestion
要从最新的 Beta 版本迁移，您需要在您的能力中添加所有核心权限标识符 `core:`，或者切换到 `core:default` 权限并删除旧的核心插件标识符。
```

2024-08-08 16:26 UTC, merged