feat: add signing docs
tauri-apps/tauri-docs pull request #2579
Opened 2024-08-24 00:50 UTC by lucasfernog

- move all signing docs to its own menu under `distribute`
- added signing for macOS, iOS, Windows, Linux
- cleaned up the android docs to align with the other ones

2024-08-26 03:21 UTC, tweidinger requested changes
Have not verified each path and that it is working as described but focused on the content.

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/concept/_recipes/glui.mdx
> +:::caution
I saw some more recipes that are not in use, not published and not supported.
Should we clean them up to only contain brownfield+isolation and delete the rest?
Shouldn't this be part of another PR?

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/macos.mdx
> +Code signing on macOS requires enrolling to the [Apple Developer] program.
```suggestion
Code signing is required on macOS to allow your application to be listed in the [Apple App Store] and to prevent a warning that your application is broken and can not be started, when downloaded from the browser.

## Prerequisites

Code signing on macOS requires enrolling to the [Apple Developer] program, which at the time of writing costs 99$ per year.
You also need an Apple device where you perform the code signing. This is required by the signing process and due to the [Apple TOS].
```

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/macos.mdx
> +See [creating a certificate signing request] to learn how to create the CSR for code signing.
`[creating a certificate signing request]` is missing a link.

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/macos.mdx
> +On your Apple Developer account, navigate to the [Certificates, IDs & Profiles page]
`[Certificates, IDs & Profiles page]` is missing a link

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/macos.mdx
> +The name of the certificate's keychain entry represents the `signing identity`, which can also be found by executing `security find-identity -v -p codesigning`.
The name of the certificate's keychain entry represents the `signing identity`, which can also be found by executing:

```sh
security find-identity -v -p codesigning
```


> Note: the Github suggestion preview seems to be a bit broken on the code blocks ending a suggestion comment 🤷  so the above is a suggestion to ease copy&paste process.

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/macos.mdx
> +4. Convert the `.p12` file to base64 running the following script on the terminal: `openssl base64 -in /path/to/certificate.p12 -out certificate-base64.txt`.
Same here, would recommend using triple backticks to allow copy&paste.

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/linux.mdx
> +This guide provides information on code signing for Linux packages.
```suggestion
This guide provides information on code signing for Linux packages.
While artifact signing is not required for your application to be deployed on Linux, it can be used to increase trust into your deployed application. Signing the binaries allows your end user to verify that these are genuine and have not been modified by another untrusted entity.

This requires you to publish your signature and public key on an authenticated channel (e.g. your website served via TLS), so the end user can download and verify.
```

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/linux.mdx
> +- gpg or gpg2
We could mention [minisign](https://jedisct1.github.io/minisign/) as a simple to use alternative.

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/windows.mdx
> +
```suggestion
Code signing is required on Windows to allow your application to be listed in the [Microsoft Store] and to prevent a [SmartScreen] warning that your application is not trusted and can not be started, when downloaded from the browser.

It is not required to execute your application on Windows, as long as your end user is okay with ignoring the [SmartScreen] warning or your user does not download via the browser.
```

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/windows.mdx
> +[bundle > windows > signCommand]: /reference/config/#signcommand
```suggestion
[bundle > windows > signCommand]: /reference/config/#signcommand
[SmartScreen]: https://en.wikipedia.org/wiki/Microsoft_SmartScreen
[Microsoft Store]: https://apps.microsoft.com/
```

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/macos.mdx
> +[Apple Developer]: https://developer.apple.com
```suggestion
[Apple Developer]: https://developer.apple.com
[Apple App Store]: https://www.apple.com/app-store/
```

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/windows.mdx
> +This guide assumes that you have a standard code signing certificate> If you have an EV certificate, which generally involves a hardware token, please follow your issuer's documentation instead.
Already covered with the big red warning above

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/windows.mdx
> +:::
I would put this at the top below the danger warning as this is relevant for everyone reading the guide and not part of the prerequisites.

Also maybe link to EV certificate and explain that EV=Extended Validation OV=Organization Validation and maybe link to a comparison page as this is a confusing topic for newcomers.

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/windows.mdx
> +1. You will need the following:
All of the numbered steps here could use the `<Steps>` feature for better user experience.

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/ios.mdx
> +Code signing on iOS requires enrolling to the [Apple Developer] program.
```suggestion
Code signing on iOS is required to distribute your application through the official [Apple App Store] or possibly alternative marketplaces in the European Union and in general to install and execute on end user devices.

## Prerequisites
Code signing on iOS requires enrolling to the [Apple Developer] program, which at the time of writing costs 99$ per year.
You also need an Apple device where you perform the code signing. This is required by the signing process and due to the [Apple TOS].
```

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/ios.mdx
> +[Apple Developer]: https://developer.apple.com
```suggestion
[Apple Developer]: https://developer.apple.com
[Apple App Store]: https://www.apple.com/app-store/
```

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/ios.mdx
> +### Automatic Signing
```suggestion
## Automatic Signing
```

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/ios.mdx
> +### Manual Signing
```suggestion
## Manual Signing
```

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/ios.mdx
> +The private key file path must be set via the APPLE_API_KEY_PATH environment variable.
```suggestion
The private key file path must be set via the `APPLE_API_KEY_PATH` environment variable.
```

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/ios.mdx
> +The APPLE_API_ISSUER (Issuer ID) is presented above the keys table, and the APPLE_API_KEY is the value on the Key ID column on that table.
```suggestion
The `APPLE_API_ISSUER` (Issuer ID) is presented above the keys table, and the `APPLE_API_KEY` is the value on the Key ID column on that table.
```

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/ios.mdx
> +To manually sign your iOS app you can provide the certificate and mobile provisioning profile via environment variables.
We should explicitly explain and add the environment variables here. They are a little bit different than in the above automated signing section.

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/ios.mdx
> +:::
```suggestion
:::tip[Choose Certificate Type]
You must use an appropriate certificate type for each export method:

- **debugging**: Apple Development or iOS App Development
- **app-store-connect**: Apple Distribution or iOS Distribution (App Store Connect and Ad Hoc)
- **ad-hoc**: Apple Distribution or iOS Distribution (App Store Connect and Ad Hoc)

:::
```

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/ios.mdx
> +After creating the provisioning profile, download it and run `base64 -i <path-to-profile.mobileprovision> | pbcopy` to convert the profile to base64 and copy it to the clipboard, and paste that value
I would suggest to make this also triple backtick for easy copy&paste

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/ios.mdx
> +Additionally, you must provide the provisioning profile for your application. In the [Identifiers](https://developer.apple.com/account/resources/identifiers/list) page, create a new App ID and make s
is the identifier meant to be a link?

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/android.mdx
> +:::note
```suggestion
:::tip
```

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/android.mdx
> +:::caution
```suggestion
:::caution[Security Warning]
```

2024-08-26 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/android.mdx
> +:::caution
```suggestion
:::caution[Security Warning]
```

Also feel having two security warnings on the same page could be condensed into one as it is about keeping secrets private.

2024-08-26 10:25 UTC, lucasfernog commented on src/content/docs/concept/_recipes/glui.mdx
> +:::caution
yep it should, i just replaced :::warning (which doesn't exist)

2024-08-26 10:26 UTC, lucasfernog commented on src/content/docs/concept/_recipes/glui.mdx
> +:::caution
```suggestion
:::warning
```

2024-08-26 10:30 UTC, lucasfernog commented on src/content/docs/distribute/Signing/macos.mdx
> +The name of the certificate's keychain entry represents the `signing identity`, which can also be found by executing `security find-identity -v -p codesigning`.
there's a way to escape that, but I don't remember now.. will take care of the suggestion

2024-08-26 13:26 UTC, lucasfernog commented on src/content/docs/distribute/Signing/linux.mdx
> +- gpg or gpg2
that's not really an option in this context - appimage only lets you embed a gpg signature

2024-08-27 03:19 UTC, tweidinger commented on src/content/docs/distribute/Signing/linux.mdx
> +- gpg or gpg2
True, was thinking this is not only Appimage as it says linux signing and Appimage only in the second heading.

2024-08-27 03:21 UTC, tweidinger commented on src/content/docs/distribute/Signing/ios.mdx
> +Code signing on iOS requires enrolling to the [Apple Developer] program.
Is this not in line with the intended flow?
I was thinking adding a one liner to explain why signing is neede for iOS would be helpful and having a dedicated prerequisites section.

2024-08-27 03:32 UTC, tweidinger approved these changes

2024-08-27 03:32 UTC, tweidinger commented
Great work ❤️

2024-08-27 03:34 UTC, merged