i18n(zh-cn): Translate `distribute/Signing/*`
tauri-apps/tauri-docs pull request #2608
Opened 2024-08-29 06:09 UTC by GuoJikun

#### Description

Includes file.

- [x]  `distribute/Signing/android.mdx`
- [x]  `distribute/Signing/ios.mdx`
- [x]  `distribute/Signing/linux.mdx`
- [ ]  `distribute/Signing/macos.mdx`
- [ ]  `distribute/Signing/windows.mdx`

2024-09-02 14:11 UTC, dklassic requested changes
Some nitpicks here and there and should be good to go!

2024-09-02 14:11 UTC, dklassic commented on src/content/docs/zh-cn/distribute/Signing/ios.mdx
> +在 iOS 上进行代码签名是必需的，以便通过官方[苹果应用商店] 或可能的欧盟替代市场分发您的应用程序，并且一般来说可以安装和执行在最终用户设备上。
```suggestion
在 iOS 上进行代码签名是必需的，以便通过官方[苹果应用商店]或可能的欧盟替代市场分发您的应用程序，并且一般来说可以安装和执行在最终用户设备上。
```
Formatting nitpick

2024-09-02 14:11 UTC, dklassic commented on src/content/docs/zh-cn/distribute/Signing/ios.mdx
> +- **IOS_MOBILE_PROVISION**: 授权描述文件的 Base64 表示。
```suggestion
要手动为你的 iOS 应用签名，你可以通过环境变量提供证书和移动配置文件：

- **IOS_CERTIFICATE**：从 Keychain 导出的证书的 base64 表示形式。
- **IOS_CERTIFICATE_PASSWORD**：从 Keychain 导出时设置的证书密码。
- **IOS_MOBILE_PROVISION**：授权描述文件的 Base64 表示。
```
Formatting nitpick

2024-09-02 14:11 UTC, dklassic commented on src/content/docs/zh-cn/distribute/Signing/ios.mdx
> +- **ad-hoc**: 苹果发行版或 iOS 发行版 (App Store Connect 和 Ad Hoc)
```suggestion
- **debugging**：苹果开发或 iOS 应用开发
- **app-store-connect**：苹果发行版或 iOS 发行版 (App Store Connect 和 Ad Hoc)
- **ad-hoc**：苹果发行版或 iOS 发行版 (App Store Connect 和 Ad Hoc)
```
Formatting nitpick

2024-09-02 14:11 UTC, dklassic commented on src/content/docs/zh-cn/distribute/Signing/ios.mdx
> +现在你可以构建你的 iOS 应用程序并在 App Store 上发布了!
```suggestion
现在你可以构建你的 iOS 应用程序并在 App Store 上发布了！
```
Formatting nitpick

2024-09-02 14:11 UTC, dklassic commented on src/content/docs/zh-cn/distribute/Signing/linux.mdx
> +- **APPIMAGETOOL_FORCE_SIGN**: 默认情况下，即使签名失败，也会生成 AppImage。要在发生错误时退出，你可以将此变量设置为 `1`。
```suggestion
- **SIGN**：设置为 `1` 为 AppImage 签名。
- **SIGN_KEY**：可选变量，用于使用特定的 GPG 密钥 ID 进行签名。
- **APPIMAGETOOL_SIGN_PASSPHRASE**：签名密钥密码。如果未设置，gpg 将显示一个对话框，以便您可以输入它。在构建 CI/CD 平台时必须设置此参数。
- **APPIMAGETOOL_FORCE_SIGN**：默认情况下，即使签名失败，也会生成 AppImage。要在发生错误时退出，你可以将此变量设置为 `1`。
```
Formatting nitpick

2024-09-02 14:11 UTC, dklassic commented on src/content/docs/zh-cn/distribute/Signing/windows.mdx
> +2. 我们将使用 [`tauri-action` 发布模板].
```suggestion
2. 我们将使用 [`tauri-action` 发布模板]。
```
Formatting nitpick

2024-09-02 14:11 UTC, dklassic commented on src/content/docs/zh-cn/distribute/Signing/windows.mdx
> +设置好所有这些变量后，运行 `tauri build` 将生成签名的Windows安装程序!
```suggestion
设置好所有这些变量后，运行 `tauri build` 将生成签名的Windows安装程序！
```
Formatting nitpick

2024-09-03 00:25 UTC, GuoJikun commented on src/content/docs/zh-cn/distribute/Signing/ios.mdx
> +打开 [App Store Connect 用户和访问页面]，选择 Keys 选项卡，单击 Add 按钮并选择名称和开发者访问权限。
```suggestion
打开 [App Store Connect 用户和访问页面]，选择 Integrations 选项卡，单击 Add 按钮并选择名称和管理员访问权限。
```

2024-09-03 00:26 UTC, GuoJikun commented on src/content/docs/zh-cn/distribute/Signing/macos.mdx
> +  打开 [App Store Connect 用户和访问页面]，选择 Keys 选项卡，单击 Add 按钮并选择名称和开发者权限。
```suggestion
  打开 [App Store Connect 用户和访问页面]，选择 Integrations 选项卡，单击 Add 按钮并选择名称和开发者权限。
```

2024-09-03 00:27 UTC, GuoJikun commented on src/content/docs/zh-cn/distribute/Signing/macos.mdx
> +  打开 [App Store Connect 用户和访问页面]，选择 Keys 选项卡，单击 Add 按钮并选择名称和开发者权限。
related: [Integrations](https://github.com/tauri-apps/tauri-docs/commit/97fa2051c7e8003cbd726c6668ad6a7c50dfaf4d)

2024-09-03 00:27 UTC, GuoJikun commented on src/content/docs/zh-cn/distribute/Signing/ios.mdx
> +打开 [App Store Connect 用户和访问页面]，选择 Keys 选项卡，单击 Add 按钮并选择名称和开发者访问权限。
related: [Integrations](https://github.com/tauri-apps/tauri-docs/commit/97fa2051c7e8003cbd726c6668ad6a7c50dfaf4d)

2024-09-03 00:48 UTC, dklassic approved these changes

2024-09-03 00:48 UTC, merged