fix: commas in JSON code block
tauri-apps/tauri-docs pull request #2754
Opened 2024-09-29 10:44 UTC by RealHinome

#### Description
- What does this PR change? Give us a brief description.
This PR addresses a comma-related issue in the V2 documentation that causes JSON formatting errors. Specifically: - a missing comma has been added; - an extraneous comma at the end of the JSON has been removed.
These changes ensure that the documentation's JSON syntax is valid and can be correctly parsed.

2024-09-29 10:47 UTC, RealHinome commented
The error is due to a formatting error; the elements are not in the right order. I'm changing that.

2024-09-29 21:25 UTC, vasfvitor requested changes
Thanks for this!

run `pnpm format` and it will fix whatever is breaking the formatting. I believe it wasn't due to the order, and they make more sense as they were before (e.g. `save-`, `get-`, `remove-` `store-record` in order), so could you please restore the original order and leave just the comma fix.

2024-09-30 11:19 UTC, RealHinome commented
I reverted my previous changes, sorry for inconvenience. As you said, it will be more idiomatic and checks will pass.

2024-09-30 12:28 UTC, tweidinger commented
Also outdated by #2759

2024-09-30 12:28 UTC, closed without merging