feat(window-menu): add docs for the `menu`
tauri-apps/tauri-docs pull request #2875
Opened 2024-10-16 08:26 UTC by RSS1102

#### Description

- What does this PR change? Give us a brief description. 

I would like to summarize and explain the use of menu

**The following problems will be solved：**
- one level menu, two (multiple) levels of settings.
-  custom menu items.
-  menu event handling.
-  reset (how to change menu status/language/etc.)

I will refer to：
- https://github.com/tauri-apps/tauri-docs/blob/7cf5fbb901e67680e20809c7ee983f863698fcf6/src/content/docs/start/migrate/from-tauri-1.mdx#migrate-to-menu-module
- https://github.com/tauri-apps/tauri-docs/blob/7cf5fbb901e67680e20809c7ee983f863698fcf6/src/content/docs/plugin/system-tray.mdx#add-a-menu

If nothing goes wrong, it will be completed within two weeks, after I have tested the code of each function (Rust has been tested, but JavaScript has not yet been tested)

**If anyone has any questions about the use of menu, please add them below. I will try my best to enrich the documentation on using menu.**

2024-11-20 02:00 UTC, RSS1102 commented
waitting https://github.com/tauri-apps/tauri/pull/11741 release.

2025-01-17 18:49 UTC, RSS1102 commented
test code https://github.com/RSS1102/tauri-app-exmaple

2025-01-20 06:42 UTC, vasfvitor requested changes
Thanks for putting this up, left some suggestions. I haven't tested the code, I trust that you did. Overall this should be enough. Thanks again. Ah, this page fits better under `/learn.` I guess, as window menu is part of Tauri Core.

2025-01-20 06:42 UTC, vasfvitor commented on src/content/docs/plugin/window-menu.mdx
> +title: Window menu
```suggestion
title: Window Menu
```

2025-01-20 06:42 UTC, vasfvitor commented on src/content/docs/plugin/window-menu.mdx
> +Native application menus can be attached to a window or can be attached to the system tray too. Available on desktop only.
```suggestion
Native application menus can be attached to both to a window or system tray. Available on desktop.
```

2025-01-20 06:42 UTC, vasfvitor commented on src/content/docs/plugin/window-menu.mdx
> +To create a base-level native window menu, and attached to the window.
```suggestion
## Creating a base-level menu

To create a base-level native window menu, and attach to a window:
```
It could be "**a** window" or "**all** windows". Is there any difference?

2025-01-20 06:42 UTC, vasfvitor commented on src/content/docs/plugin/window-menu.mdx
> +//  If a window was not created with an explicit menu or had one set explicitly,
```suggestion
// If a window was not created with an explicit menu or had one set explicitly,
```
Same, is this window specific? What if I want to attach to all windows? Or is it always to all of them?

2025-01-20 06:42 UTC, vasfvitor commented on src/content/docs/plugin/window-menu.mdx
> +Each custom menu item triggers an event when clicked. Use the on_menu_event API to handle them.
```suggestion
Each custom menu item triggers an event when clicked. Use the `on_menu_event` API to handle them.
```
do you know if is there any doc reference to `on_menu_event`? Also since it's Rust specific, would be better to move it to be visible only when "Rust" tab is active

2025-01-20 06:42 UTC, vasfvitor commented on src/content/docs/plugin/window-menu.mdx
> +To create a multi-level menu, you can add some submenus to the menu item.
```suggestion
To create a multi-level menu, you can add some submenus to the menu item:
```

2025-01-20 06:42 UTC, vasfvitor commented on src/content/docs/plugin/window-menu.mdx
> +fn main() {
in this section both tabs has Rust code in it

2025-01-20 06:42 UTC, vasfvitor commented on src/content/docs/plugin/window-menu.mdx
> +Note that you need the image-ico or image-png Cargo features to use this API. To enable it, change your Cargo.toml file:
```suggestion
Note that you need to enable `image-ico` or `image-png` feature to use this API:
```

2025-01-20 06:42 UTC, vasfvitor commented on src/content/docs/plugin/window-menu.mdx
> +```
```suggestion
```toml title="src-tauri/Cargo.toml"
[dependencies]
tauri = { version = "...", features = ["...", "image-png"] }
```
```

2025-01-20 06:42 UTC, vasfvitor commented on src/content/docs/plugin/window-menu.mdx
> +To create predefined (native) menu item which has a predefined behavior by the OS or by tauri.
```suggestion
To use built-in (native) menu items that has predefined behavior by the operating system or Tauri:
```

2025-01-20 06:42 UTC, vasfvitor commented on src/content/docs/plugin/window-menu.mdx
> +:::
If possible move to the Rust tab, I'm not sure if it would look good

2025-01-20 06:42 UTC, vasfvitor commented on src/content/docs/plugin/window-menu.mdx
> +If you want to change the status of the menu, such as text, icon, check status, you should `set_menu` again.
```suggestion
If you want to change the status of the menu, such as text, icon, or check status, you can `set_menu` again:
```

2025-01-20 06:44 UTC, vasfvitor commented
also I'm thinking if somehow this can be split into more sections and not only top level headings, not if possible, just an idea
![image](https://github.com/user-attachments/assets/49fad28f-91a6-4ff1-ad10-fc838b5c4cc5)

2025-02-07 02:03 UTC, RSS1102 commented on src/content/docs/plugin/window-menu.mdx
> +To create a base-level native window menu, and attached to the window.
There seems to be no difference in the adjectives, but I remember there is an API that can add different effects to a `window menu` for a specific window.

2025-02-07 02:06 UTC, RSS1102 commented
> also I'm thinking if somehow this can be split into more logical sections and not only top level headings, not sure it's possible, just an idea ![image](https://private-user-images.githubusercontent.com/61759797/404767430-49fad28f-91a6-4ff1-ad10-fc838b5c4cc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg4OTQxOTQsIm5iZiI6MTczODg5Mzg5NCwicGF0aCI6Ii82MTc1OTc5Ny80MDQ3Njc0MzAtNDlmYWQyOGYtOTFhNi00ZmYxLWFkMTAtZmM4MzhiNWM0Y2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjA3VDAyMDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmNWQ5MTNlMzY5MTJjZGFiZTUxODNkMzIzMDEzZTc2OWYwMDIzYTEzNmNhNTMyNjI3OTg2NzI2YjMwOWJjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oG5QYxhbc4As3c1SDshKB2W26aY6PXLiMdF1rG8Vh3E)
> 
> more like this ![image](https://private-user-images.githubusercontent.com/61759797/404767773-fc75d4ef-eda2-49a7-a9d5-acf05096958b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg4OTQxOTQsIm5iZiI6MTczODg5Mzg5NCwicGF0aCI6Ii82MTc1OTc5Ny80MDQ3Njc3NzMtZmM3NWQ0ZWYtZWRhMi00OWE3LWE5ZDUtYWNmMDUwOTY5NThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjA3VDAyMDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0Y2JlYTkwM2IxMTA1ZDcyYWI5NDFjMGU0YzhjYTAwNjc3MTliZjY0OTkyYmQwYTNiMzZhOGZkZmE5OThiMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r3SSi_JO9bSlk7pT_I0nEnVda2Fa4S3LG5oH1JX2CBs)

Maybe I will optimize this in the future, but it seems that I am delayed by other things and I don’t have the energy to re-plan all the code at the moment. But I will keep it in mind and optimize it later.

2025-02-07 03:11 UTC, vasfvitor commented
@RSS1102 it's ok, I can merge already and it can be improved later, what do you think?

2025-02-07 03:13 UTC, RSS1102 commented
> @RSS1102 it's ok, I can merge already and it can be improved later, what do you think?

ok,In the next stage, I will synchronize the Chinese version first.
 And then I will make an improvement (when my time permits).

2025-02-07 03:23 UTC, merged

2025-02-07 03:23 UTC, vasfvitor commented
thank you for this