The default terminal is now zsh
tauri-apps/tauri-docs pull request #293
Opened 2021-10-15 10:39 UTC by pauleaster

On a Mac, executing this fails if running zsh, which is now the default:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
Whereas this seems to work:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | zsh

PS: This is my first public PR, so I hope I did it correctly!

2021-10-15 15:42 UTC, nothingismagick requested changes
Hmm. Well, maybe we could be even smarter about it and just use whatever the user has that is able to run shell scripts. Maybe confirm if this works for you as it does for me. (also, nvm has been updated, so might as well update the version too):
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | sh
```

2021-10-26 05:16 UTC, pauleaster commented
Yes, this works for me.

2021-10-27 15:03 UTC, nothingismagick commented
Thanks!!!

2021-10-27 15:03 UTC, nothingismagick approved these changes

2021-10-27 15:04 UTC, merged