Add basic PWA configuration
tauri-apps/tauri-docs pull request #612
Opened 2022-05-18 08:16 UTC by HyunseungLee-Travis

# Draft

2022-05-18 19:19 UTC, lorenzolewis requested changes
I like the direction of this and don't see a downside. At first was worried about adding build time but only increased CI build time by like 3 seconds.

For the notes on images, let me know if you'd like me to help on that and I can throw together the proper images very quickly.

2022-05-18 19:19 UTC, lorenzolewis commented on docusaurus.config.js
> +          'saveData',
I don't know much about PWAs, but do you understand the strategies for [offline mode activation strategies](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-pwa#offlinemodeactivationstrategies)? I'm curious of the caution annotation in that section. `appInstalled` and `standalone` that you have sound like they're opt-in so fine. I read `queryString` as something that maybe we don't want as it's used for debugging? `saveData` seems fine.

2022-05-18 19:19 UTC, lorenzolewis commented on docusaurus.config.js
> +            name: 'theme-color',
Do you know if it's possible to toggle these based on colour mode? Or to use a css variable instead? If we can use a css variable then `var(--ifm-color-primary)` would be nice to try

2022-05-18 19:19 UTC, lorenzolewis commented on docusaurus.config.js
> +            name: 'apple-mobile-web-app-status-bar-style',
Same comment as above about if we can change colours dynamically

2022-05-18 19:19 UTC, lorenzolewis commented on docusaurus.config.js
> +            href: '/img/favicon-96x96.png',
This image should be 180x180 pixels per Apple's HIG https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/

2022-05-18 19:19 UTC, lorenzolewis commented on docusaurus.config.js
> +            href: '/img/favicon-96x96.png',
Should also be a solid background, not transparent

2022-05-18 19:19 UTC, lorenzolewis commented on docusaurus.config.js
> +            content: '/img/favicon-96x96.png',
I'm not sure about sizes on this one, does it need to be larger?

2022-05-18 19:19 UTC, lorenzolewis commented on package.json
> +    "@docusaurus/plugin-pwa": "^2.0.0-beta.20",
Remove the carot (^) from here, our dep checker will do it in another PR as soon as this is merged if not ;)

2022-05-18 19:19 UTC, lorenzolewis commented on static/manifest.json
> +      "sizes": "512x512",
See note in config about image pixelation

2022-05-18 19:19 UTC, lorenzolewis commented on static/manifest.json
> +  "theme_color": "#1A1A1D",
Same comment on colour, can we use a CSS variable?

2022-05-18 19:19 UTC, lorenzolewis commented on static/manifest.json
> +  "shortcuts": [
I like the idea of the shortcuts, but I'm worried about urls changing in the future (especially since they now have version numbers in them) and breaking. I'd opt to not have any shortcuts.

2022-05-18 23:21 UTC, hslee2008 commented on docusaurus.config.js
> +            content: '/img/favicon-96x96.png',
I think it needs to be 144x144. I saw some example code for msapplication-TileImage and all of them had the size of 144x144.

2022-05-19 10:07 UTC, lorenzolewis commented
![iOS Icon](https://user-images.githubusercontent.com/15347255/169268641-1536c479-3199-40aa-8f6b-4db4c91fb9de.png)
Can you use this file for the `apple-touch-icon` (will match up to the default Tauri icon on macOS)? Keep the current size because technically 1024x1024 is the largest iOS app size you export with an app, so should keep us future-proof.

2022-05-19 10:14 UTC, lorenzolewis commented
![Tauri Logo](https://user-images.githubusercontent.com/15347255/169270181-c1e72821-dd34-4f69-b1f9-66abc66a45c3.svg)
And this is the vector for the logo if you'd like to re-render the other files so they aren't pixelated

2022-05-19 10:17 UTC, lorenzolewis commented
I'd recommend having a margin around the edges of the files the width of one of the blue/yellow circles in the logo

2022-05-19 21:31 UTC, lorenzolewis commented
I'll make the images and include the margins tomorrow and put them here.

2022-05-20 08:51 UTC, lorenzolewis commented
![favicon144](https://user-images.githubusercontent.com/15347255/169489057-08e65c42-800b-4932-ac42-2d82919957fb.png)
![favicon512](https://user-images.githubusercontent.com/15347255/169489066-0f809bbd-1864-4502-b316-98ccc50db5dd.png)

Here are these two. What's the maskable image used for? I think the 512 image should be able to work for both of them now since it's transparent? 

If you're running Windows can you give a screenshot of what the app icon looks like on the start menu and taskbar?

2022-05-20 09:04 UTC, lorenzolewis commented
Just noticing that static/img/favicon-32x32.png is actually 31 pixels instead of 32 now. I think the original file that was there is fine (and the right size) but seems to be modified. 

Then lastly moving all the files into `static/meta` (images and manifests) just to keep that folder a bit more organised.

2022-05-20 09:12 UTC, lorenzolewis commented
What was the outcome on separate manifests for dark/light mode? I'm putting in reviews for the theme colours but we have different ones depending on if it's dark or light, so was that able to be dynamic?

2022-05-20 09:15 UTC, lorenzolewis commented on docusaurus.config.js
> +            content: '#1B1B1D',
```suggestion
            content: '#0F0F0F',
```

2022-05-20 09:15 UTC, lorenzolewis commented on docusaurus.config.js
> +            color: '#1B1B1D',
```suggestion
            color: '#0F0F0F',
```

2022-05-20 09:15 UTC, lorenzolewis commented on docusaurus.config.js
> +            content: '#1B1B1D',
```suggestion
            content: '#0F0F0F',
```

2022-05-20 09:15 UTC, lorenzolewis commented on static/manifest.json
> +  "background_color": "#1B1B1D",
```suggestion
  "background_color": "#0F0F0F",
```

2022-05-20 09:15 UTC, lorenzolewis commented on static/meta/manifest.json
> +  "background_color": "#1B1B1D",
```suggestion
  "background_color": "#0F0F0F",
```

2022-05-20 09:15 UTC, lorenzolewis commented on static/meta/manifest.json
> +      "url": "https://tauri.studio/manifest.json"
Should this be set to meta/manifest.json now?

2022-05-20 09:20 UTC, lorenzolewis commented
Okay, I'll go through and suggest neutral colours on the theme then. Better to have that than a clash I think.

2022-05-20 09:31 UTC, lorenzolewis commented on docusaurus.config.js
> +            content: '#2196f3',
```suggestion
            content: '#0F0F0F',
```

2022-05-20 09:31 UTC, lorenzolewis commented on static/meta/manifest.json
> +    }
Is this needed if it's pointing to the same image as the above lines?

2022-05-20 09:31 UTC, lorenzolewis commented on static/meta/manifest.json
> +  "theme_color": "#2196f3",
```suggestion
  "theme_color": "#0F0F0F",
```

2022-05-20 09:31 UTC, lorenzolewis commented on docusaurus.config.js
> +            href: '/img/favicon-apple-touch-icon.png',
Can this point to the one in the meta folder and then remove the one in the 'img' folder?

2022-05-20 09:31 UTC, lorenzolewis commented on static/meta/manifest.json
> +      "src": "/img/favicon-16x16.png",
Can we move this file to meta and change the src here?

2022-05-20 09:31 UTC, lorenzolewis commented on static/meta/manifest.json
> +      "src": "/img/favicon-32x32.png",
Same, move file, update source

2022-05-20 09:31 UTC, lorenzolewis commented
Sorry for the million back and forths, but almost there!

2022-05-20 09:54 UTC, lorenzolewis commented
Which other files are they used in? It would probably make sense to update where those files are pointing then if possible

2022-05-20 09:56 UTC, lorenzolewis commented
Are you able to use yarn instead of npm to update yarn.lock? Right now it's changing all of the urls for every package which isn't ideal. If not then I can go back through and switch it over on my computer.

2022-05-20 09:58 UTC, lorenzolewis commented
I'll probably do some additional cleanup later for other assets, so just updating those for now is perfect

2022-05-20 10:02 UTC, lorenzolewis approved these changes

2022-05-20 10:05 UTC, lorenzolewis commented
Looks good, but I want to get a Netlify deploy preview up and running first before merging. Not sure why it's paused, so I'll give a shout to the team over in Discord

2022-05-20 10:20 UTC, lorenzolewis commented
Thanks for the netlify nudge @Laegel ;)

2022-05-20 10:24 UTC, lorenzolewis commented
![image](https://user-images.githubusercontent.com/15347255/169508519-ef7f1cc2-da70-4bd2-98a4-5ddb278e92e1.png)

I'm going to tweak this image very slightly because of the corner artefacts

2022-05-20 10:40 UTC, lorenzolewis commented
![iOS Icon](https://user-images.githubusercontent.com/15347255/169511202-adca2761-64f3-4388-a0f5-0a5b669e8e8a.png)

Could you swap it to this one please?

2022-05-20 11:15 UTC, lorenzolewis commented
When you launch it looks like it's trying to go to `/meta/`

2022-05-20 11:16 UTC, lorenzolewis commented on static/meta/manifest.json
> +  "start_url": ".",
```suggestion
  "start_url": "/",
```

2022-05-20 11:16 UTC, lorenzolewis commented on static/meta/manifest.json
> +  "start_url": ".",
I wonder if this will fix it

2022-05-20 11:24 UTC, lorenzolewis commented
Need another approval on Netlify from the gods because we're close to our CI minutes @Laegel

2022-05-20 12:01 UTC, lorenzolewis commented
Fixed for iOS, how about Android?

2022-05-20 12:03 UTC, Laegel approved these changes

2022-05-20 12:18 UTC, lorenzolewis commented
@HyunseungLee-Travis can you verify you commits and then push some test again (just add a newline or a comment somewhere)? We're thinking that's why the previews stopped (and would be good practice to have all commits verified).

2022-05-20 21:06 UTC, hslee2008 commented
Works in Android.

2022-05-20 21:36 UTC, merged

2022-05-20 21:36 UTC, lorenzolewis commented
Awesome job, thank you very much!